### ISSUE TITLE
Fix CodeQL alert 25

### ISSUE THREAD

**Issue by KyleA99** [hackforla/website#5749] opened 2023-10-22 05:06 UTC
### Overview
We need to delete the malformed attribute id, id="" because blank id attributes are not considered valid.

### Action Items
- [x] In your IDE, open the _includes/wins-page/wins-filter-template.html file
- [x] On line 14 (shown below), delete the invalid blank id attribute, id="".
`<input type="checkbox" id="" name="" value="" class="old-filter-checkbox" />`
- [x] Save wins-filter-template.html and test locally in docker to ensure no issues/errors were created.
- [x] Create a Pull Request in the usual manner, with changes only to wins-filter-template.html.

### Resources/Instructions
Reference links:
- Resolve CodeQL alert 25 #5642
- https://github.com/hackforla/website/security/code-scanning/25

**Comment by roslynwythe** [comment] 2023-10-22 08:34
@KyleA99 Please note, new issues must go through an approval process before they can be assigned.  I'm temporarily putting this back into New Issue Approval.

**Comment by roslynwythe** [comment] 2024-01-30 02:05
The author was working on a different issue and thought he needed this issue, but it is duplicate of #5642

**Closed as not planned** 2024-01-30 02:06 UTC
Labels: role: front end, Feature: Accessibility, Complexity: Small, Feature: Refactor HTML, ready for dev lead, Ignore: Duplicate, size: 0.25pt, Feature: Code Alerts
