### ISSUE TITLE
Create new About page

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#493] opened 2020-05-03 22:53 UTC
### Overview
Create new About page that links to existing About link in navigation. This section will include such elements as the organization's missions statement, leadership, operating structure of hack night meeting. The section may also take over content currently in the FAQ section of the Getting Started page.

### Action Items
- [ ] Draft copy for About page
- [ ] Create wireframe for page
- [ ] Create mockup for page

**Comment by alexandrastubbs** [comment] 2020-10-22 22:31
Duplicate of https://github.com/hackforla/website/issues/614. Closing.

**Closed as completed by alexandrastubbs** 2020-10-22 22:31 UTC
Labels: Ignore: Duplicate
