### ISSUE TITLE
ER: Add-Missing-Labels-to-Issues job fails when opening an issue

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#4129] opened 2023-03-08 02:10 UTC
### Emergent Requirement - Problem
- Every time after I click the "Submit new issue" button and open an issue, I get a notification that the Add-Missing-Labels-To-Issues job failed.
- Link to a failed workflow: https://github.com/hackforla/website/actions/runs/4348262408
  <details>
    <summary>Click here to see a screenshot of the failed workflow</summary>
    <img src="https://user-images.githubusercontent.com/31293603/223601607-476d03b7-60fa-4c53-bd5b-7e6e59860611.png" alt="">
  </details>

  - Workflow showed 1 error and 2 warnings.
    - > [Add-Missing-Labels-To-Issues](https://github.com/hackforla/website/actions/runs/4348262408/jobs/7596570234#step:4:58)
  Bad credentials
    - > [Add-Missing-Labels-To-Issues](https://github.com/hackforla/website/actions/runs/4348262408/jobs/7596570234)
  Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/github-script@v4, tspascoal/get-user-teams-membership@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
    - > [Add-Missing-Labels-To-Issues](https://github.com/hackforla/website/actions/runs/4348262408/jobs/7596570234#step:3:94)
  The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
- After updating the Teams token, the `Bad credentials` error was fixed but we've run into a different error in the workflow. Link to a workflow run after updating Teams token: https://github.com/hackforla/website/actions/runs/4422133435
  <details>
    <summary>Click here to see a screenshot of the failed workflow after updating Teams token</summary>
    <img src="https://user-images.githubusercontent.com/31293603/225417309-34a905b8-c428-40fd-8377-735a0bdb199b.png" alt="">
  </details>

  - The error is
    - > [Add-Missing-Labels-To-Issues](https://github.com/hackforla/website/actions/runs/4422133435/jobs/7753636773#step:5:18)
Unhandled error: Error: HttpError: Invalid request. For 'links/0/schema', nil is not an object.

### Issue you discovered this emergent requirement in
- #4120 

### Date Discovered 
Noticed it on March 6, 2022. However, I think the Add-Missing-Labels-To-Issues job has been failing for at least a few months now if you look at the logs for issues that are opened: https://github.com/hackforla/website/actions/workflows/issue-trigger.yml.

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
GitHub Handle: JessicaLucindaCheng
GitHub Handle: jdingeman

### What happens if this is not addressed
- For me, I just get a notification every time I open a new issue since I usually add all the labels and add the issue to the Project Board before I click "Submit new issue". So, it isn't really a big deal for me.
- Deprecated items may cause further issues in the future, which include "The `set-output` command is deprecated..." warning from before updating the Teams token. Thus, I think all the deprecated items need to be addressed.

### Recommended Action Items
- [x] Make a new issue
- [x] Discuss with team
- [x] Let a Team Lead know

### Potential solutions [draft]
- Updating the TEAMS token fixed the "Bad credentials" error only. All the deprecated feature warnings still need to be fixed.

**Comment by jdingeman** [comment] 2023-03-15 02:40
Issue for this ER has been made here
- https://github.com/hackforla/website/issues/4189

@JessicaLucindaCheng - let me know if the issue is clear. 

Closing this issue

**Closed as completed by jdingeman** 2023-03-15 02:40 UTC
Labels: Complexity: Medium, Feature: Board/GitHub Maintenance, role: dev leads, size: 0.25pt, ER

**Comment by JessicaLucindaCheng** [comment] 2023-03-15 19:35
@jdingeman
> Issue for this ER has been made here
> 
> * [Fix the Add-Missing-Labels-to-Issues job error #4189](https://github.com/hackforla/website/issues/4189)
> 
> @JessicaLucindaCheng - let me know if the issue is clear.
> 
> Closing this issue

- See my comment here: https://github.com/hackforla/website/issues/4189#issuecomment-1470735951
