### ISSUE TITLE
ER: Create issues so that we correctly use quotes around text in Templates .md files

### ISSUE THREAD

**Issue by codyyjxn** [hackforla/website#7577] opened 2024-10-08 15:57 UTC
### Emergent Requirement - Problem
Inconsistent formatting rules for when to use quotes in markdown files. We need to add quotes to the markdown files to have a consistency around the project. 

### Issue you discovered this emergent requirement in
- #7540

We need to create issues to add quotes on every dropdown. As shown below. 

https://github.com/hackforla/website/blob/271a82e89f55bdeeb80677403558228aee2bbe24/.github/ISSUE_TEMPLATE/project-profile-card-review-and-update.yml?plain=1#L224

https://github.com/hackforla/website/blob/271a82e89f55bdeeb80677403558228aee2bbe24/.github/ISSUE_TEMPLATE/project-profile-card-review-and-update.yml?plain=1#L233

### Date discovered 
2024-09-29

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@ExperimentsInHonesty @kgold2018

### What happens if this is not addressed
If this isn't addressed the developers are confused. 

### Resources
https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/project-profile-card-review-and-update.yml?plain

### Recommended Action Items
- [ ] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

### Potential solutions [draft]

- [ ] Create an issue using Blank Issue Template, or by clicking [here](https://github.com/hackforla/website/issues/new?assignees=&labels=Complexity%3A+Missing%2C+Feature+Missing%2C+role+missing%2C+size%3A+missing&projects=&template=blank-issue-template.md&title=)
- [ ]  Change the Title to Fix quotes of "Slack Link" in Issue Template [INSERT_FILE_NAME], replace [INSERT_FILE_NAME] with the file name
- [ ] Open the file `[INSERT_PATH_TO_FILE]` in your code editor 
- [ ] On Line [INSERT_LINE_NUMBER] , replace every dropdown label that does not have quotes with quotes.

**Comment by codyyjxn** [comment] 2024-10-08 16:01
@ExperimentsInHonesty Hi Bonnie thank you for clarify the problem that I was having. I now made the correct change I believe. If anything is wrong with this I am more than happy to fix this, also is it ok if I have the "New Issue Approval" label ?

**Comment by ExperimentsInHonesty** [comment] 2024-10-25 17:59
duplicate of https://github.com/hackforla/website/issues/7540

**Closed as not planned by ExperimentsInHonesty** 2024-10-25 17:59 UTC
Labels: good first issue, role: front end, Complexity: Medium, Feature: Standards, Ignore: Duplicate, size: 0.25pt, Issue Making: Level 2, ER
