### ISSUE TITLE
Modifying reusable class components

### ISSUE THREAD

**Issue by leonelRos** [hackforla/website#643] opened 2020-07-26 18:35 UTC
### Overview

We need to find the pull request that is reducing the margin at the top of all pages on the HfLA site. 

### Action Items 

 - [ ] Check merged PR to find the reusable class component that was modified.
 - [ ] Check current pages on the website for a possible layout failure
 - [ ] One the pull request that caused this is identified, talk with developer who submitted to understand reason why change was made in order to ideate a solution together 

<img width="1407" alt="Screen Shot 2020-07-26 at 10 48 33 AM" src="https://user-images.githubusercontent.com/50648001/88485790-84665b80-cf2d-11ea-93f7-c9c08a30f6e2.png">

<img width="1018" alt="Screen Shot 2020-07-26 at 10 49 07 AM" src="https://user-images.githubusercontent.com/50648001/88485799-98aa5880-cf2d-11ea-88f2-310519beccaf.png">

**Comment by ExperimentsInHonesty** [comment] 2020-07-29 03:37
duplicate of #651

**Closed as completed by ExperimentsInHonesty** 2020-07-29 03:37 UTC
Labels: Bug, Ignore: Duplicate
