### ISSUE TITLE
Google Apps Script: Fix data errors in spreadsheet used for wins page

### ISSUE THREAD

**Issue by SAUMILDHANKAR** [hackforla/website#2901] opened 2022-02-28 07:52 UTC
### Overview
The data used to generate our wins page should be error free. For this issue, we will analyze and fix the data discrepancies between the responses and review sheets used to build the wins page.

### Action Items
- [x] This issue was reopened because it failed the QA.  Read through the comments, look at the PR, and then tackle this issue
- [x] Obtain access to the Google Apps Script in the admin drive from the technical lead
- [x] Become familiar with the workflow process in creating a wins entry
- [x] In the admin drive, create a copy of the Wins-form (Responses) and Secret files in your own drive to recreate the workflow
- [ ] Identify the reason for data discrepancy between the responses and review sheets 
- [ ] Fix the code logic so that the data is consistent amongst various sheets
- [ ] Add an error catching mechanism so that error like this is not repeated again
- [ ] From this [comment](https://github.com/hackforla/website/pull/2765#issuecomment-1036942313), fix the following problems:
   - [ ] There is something wrong with the Wins spreadsheet, where Wins form entry made on 11/5/2021 wasn't added to the Review sheet and so the true/false in the "Display?" and "Homepage?" are off.
- [ ] Test the code so that on a new form submit, both the Review sheet and Responses sheet gets updated appropriately
  - [ ] See this [comment](https://github.com/hackforla/website/issues/2901#issuecomment-1328166222)
- [ ] Demo the code to the technical lead and team

For merge team:
- [ ] Once approved, update the current production code
- [ ] Release dependency on #2385 and #2505
  - [ ] Update action items in the dependency issue if needed 

### Resources/Instructions
[Google Apps Script](https://developers.google.com/apps-script/overview)
[_wins-data file](https://github.com/hackforla/website/blob/gh-pages/_data/external/_wins-data.json)
[wins page JS](https://github.com/hackforla/website/blob/gh-pages/assets/js/wins.js)
[Response sheet](https://docs.google.com/spreadsheets/d/1fXmYrmNtrgdzkM_odGIRbSwdaea3yS0cTLCJUzZ6Sc0/edit#gid=1301054877)

**Comment by luke-karis** [comment] 2022-03-16 01:47
ETA: March 23
Availability: Monday, Tuesday, Wednesday from 4 pm - 5 pm, Saturday and Sunday 10 am - 12 pm

**Comment by luke-karis** [comment] 2022-03-23 02:02
Updated ETA and Availability:
ETA: March 28
Availability Friday, Saturday, Sunday 1-2 hours each day
Progress: Got access to Drive folder, I plan to really get going on this during the weekend
Blockers: None

**Comment by JessicaLucindaCheng** [comment] 2022-03-24 23:27
@luke-karis Thanks for providing an updated ETA and availability but if you are providing a progress update please also include   Progress and Blockers. Here is more information about providing a progress update: https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#25-reporting-progress-on-your-issue

Once you have completed a progress report that includes progress, blocker, availability, and ETA, you can check off that item in your [pre-work checklist](https://github.com/hackforla/website/issues/2727) and then check off the "Once all tasks are completed, close this issue." task and then close your pre-work issue. Thanks.

**Comment by luke-karis** [comment] 2022-04-04 03:41
Updated ETA and Availability:
ETA: April 8
Availability: Monday, Tuesday, Wednesday, Thursday 4-5/5:30 pm
Progress: Started working on figuring out what the issue is
Blockers: none

**Comment by luke-karis** [comment] 2022-04-12 05:44
ETA and Availability:
ETA: April 18
Availability: Tuesday 5:00-7:00, Thursday 4:00-5:00, Saturday and Sunday 10:00-12:00
Blockers: Kinda, but a little hard to articulate. I'm going to work more on this on Tuesday and hopefully come up with blockers to bring up a stand up.

**Comment by JessicaLucindaCheng** [comment] 2022-04-20 23:07
@SAUMILDHANKAR I changed your Action Item
> - [ ] Make sure the issues mentioned in the following comment are resolved: https://github.com/hackforla/website/pull/2765#issuecomment-1036942313

to 

> - [ ] From this [comment](https://github.com/hackforla/website/pull/2765#issuecomment-1036942313), fix the following problems:
>   - [ ] In the _wins-data.json and wins-data.json at the end of each Wins entry, there is `"":""`, which wasn't there in the current _wins-data.json and current wins-data.json in gh-pages.
>   - [ ] There is something wrong with the Wins spreadsheet, where Wins form entry made on 11/5/2021 wasn't added to the Review sheet and so the true/false in the "Display?" and "Homepage?" are off.


This removes the problem "Also, for _wins-data.json, UniqueID shouldn't be there yet because the Google Apps Script related to issue https://github.com/hackforla/website/issues/2385 hasn't been added to the product script.", which needs to be addressed in a separate issue.

**Comment by luke-karis** [comment] 2022-04-21 00:21
ETA and Availability Update:
ETA: 4/27
Availability: Sunday 4/25 - Wednesday 4/27 for 1-2 hours each day (assuming I'm feeling better)
Blockers: I'm been feeling a little sick this past week so I haven't made a lot of progress on this. Hopefully I'll feel better soon and be able to work on this during my availability.

**Comment by luke-karis** [comment] 2022-05-03 05:30
ETA and availability update:
Progress: Started working on the scripts in the admin drive rather than my janky copy and pasted one. Unfortunately not too much other progress to report 
ETA: 5/9/22
Availability: Monday 1 hour, Tuesday 1-2 hours, Wednesday (maybe) 1 hour, Saturday and Sunday 1-2 hours
Blockers: none

**Comment by JessicaLucindaCheng** [comment] 2022-05-11 23:27
@luke-karis Please provide a progress update with Progress, Blockers, Availability, and ETA

**Comment by luke-karis** [comment] 2022-05-17 00:26
ETA and Availability Update:
ETA: 5/25
Availability: Monday, Tuesday 1-2 hours
Blockers: None

**Comment by luke-karis** [comment] 2022-06-01 00:34
ETA and Availability Update:
ETA: 6/7/22
Availability: Thursday, Friday, Saturday, Sunday, Monday, Tuesday 1-2 hours
Blockers: None

**Comment by luke-karis** [comment] 2022-06-15 00:32
ETA and Availability Update:
ETA: 6/21/22
Availability: Wednesday 1.5-2 hours, Saturday 1 hour, Sunday 2-3 hours, Monday all damn day if I need to
Blockers: None

**Comment by luke-karis** [comment] 2022-06-21 02:44
ETA and Availability Update
ETA: June 28
Availability: Friday, Saturday, Sunday 2-3 hours 
Blockers: None

**Comment by luke-karis** [comment] 2022-07-13 01:13
ETA and Availability Update
ETA: July 15
Availability: Tuesday, Thursday 1-2 hours
Blockers: None

**Comment by luke-karis** [comment] 2022-07-20 02:29
ETA and Availability Update
ETA: July 21
Availability: Wednesday, Thursday 1-2 hours
Blockers: None

**Comment by luke-karis** [comment] 2022-08-20 22:21
ETA and Availability Update
ETA: August 23
Availability: N/A
Blockers None

This is done I just need the go ahead to actually implement my code changes in the main scripts. Hopefully I will be able to do that at this Tuesday's meeting

**Comment by luke-karis** [comment] 2022-09-18 02:24
This is finally done!

**Comment by kathrynsilvaconway** [comment] 2022-09-18 04:39
We have demoed the changes and this issue is now complete.

**Comment by ExperimentsInHonesty** [comment] 2022-11-27 04:02
It says this issue is complete, but I added a true to one of the responses over a week ago, and it's still not showing up.  There are some items that are unchecked for the merge team.  Please review.

**Comment by jdingeman** [comment] 2023-01-10 00:19
Reopening issue per Bonnie's comment that a "True" response has not shown up in the Wins page.

**Comment by roslynwythe** [comment] 2023-01-16 00:01
Availability: 1/15: 4-5:30 pm ; 1/16 10-noon, 3-5 pm; 1/17 1 -4 pm; 1/18 noon - 5 pm
ETA: 1/22/2022

**Comment by roslynwythe** [comment] 2023-01-17 05:26
@jdingeman This issue was reopened because Bonnie had noticed that when she changed display to TRUE on a wins entry, it was not displaying.  After testing, I could not find evidence of the bug originally described in this issue.  I believe the behavior Bonnie observed is due to the fact that _wins-data.json is no longer being posted to GitHub, due to the out of date token, so no updates to wins data can be expected.  

The last merge of data from the PR https://github.com/hackforla/website/pull/3024#issue-1189380440
 is dated Nov 1, 2022.  However, when I run git log -p _wins-data.json, it gives a date of Dec. 2, 2021 (commit 3b178e7).  Several reasons were given for the pause in merging, but based on this comment:  https://github.com/hackforla/website/issues/3417#issuecomment-1291344555   it sounds like the previous problems with the _wins-data.json feed were resolved and so the outstanding issue is that the GH wins token needs to be updated: https://github.com/hackforla/website/issues/3748#issue-1465544027

While debugging the app script, I examined the wins json feed prior to base64 encoding, and I saw no evidence of the previously reported problems such as empty JSON field or UniqueIDs.  

If an additional error catching mechanism is desired for the bug in which Review and Response get out of sync, I suggest that in the function "createIssue" in code.gs, we check for an equal number of rows in Review and Response sheets, and if they are not equal, we a new GitHub issue to indicate the error.  We should do the same in 'main', and if Review and Response do have an equal number of rows, we should not send a wins json feed to GitHub.  That would be more a complex mechanism than was already created, because it will involve also changes to the ghrequest library code, but it would be a more effective mechanism.

**Comment by roslynwythe** [comment] 2023-01-17 06:08
Progress:
1. After the first 4 action items were created, I manually ran the function "compareResponsesAndReview" which confirmed that the Review and Response sheets are "in sync".  
2. I ran main in debugging mode and noted that it failed due to "bad credentials".  
3. While debugging main, I looked at the wins json feed {cleanedAndFormattedKeyValueData} prior to base64 encoding and noted that it looked fine.  There were no empty JSON fields and no UniqueIDs.  
4. I reviewed the existing error catching mechanism.  If an more extensive error catching mechanism is desired, I suggest that before posting the GitHub issue for review of new wins submissions, in the function "createIssue", we check for an equal number of rows between Review and Response sheets, and if a problem is detected, we create a bug report GitHub issue instead of a "review" GitHub issue.  We can also do a check in main prior to posting the _wins-data.json feed.  If there are an unequal number of rows in the Review and Response sheets, we shouldn't generate the _wins-data.json feed.

**Comment by jdingeman** [comment] 2023-01-21 08:41
Hi @roslynwythe, I think I'm finally understanding how the Google Apps Script is "integrated" into the repo, and it is quite strange to be honest. It seems that the changes are only committed to #3024 when the script is ran manually and successfully. I just ran it a few minutes ago and saw that the changes in Leon's issue #2675 were implemented, but they were not published to the site. If you have time to meet some time in the next week, I'd like to hear your explanation face to face so I can get a better understanding from your perspective.

**Comment by ExperimentsInHonesty** [comment] 2023-01-22 17:29
@roslynwythe @jdingeman it looks like you both are working on this issue, so I am going to put it into the in progress column.  Please move issues there when you self assign.

**Comment by jdingeman** [comment] 2023-01-25 01:26
Met with dev to discuss how to move forward with issue. Determined that changes made in the Google Apps Script does not cause any bugs and is being pushed into #3024 which is not merged yet.

@ExperimentsInHonesty - the reason the changes haven't appeared on the website is because the PR that's holding all the changes going into the .json file hasn't been merged. Right now, the website only displays the data that's in the repo's current wins-data.json and that gets updated when the data coming from the Google Apps Script gets pushed and merged. 

I let dev know that we will discuss this issue technically being satisfied since the bug was fixed on the script itself, but won't appear until #3024 is merged. I think when all issues related to Google Apps Script have been finished and satisfied on the script side, we can merge the PR so that changes are put on the published site.

Dev suggested optimizing the debugging methods and will write up a new issue for review.

**Comment by roslynwythe** [comment] 2023-01-27 21:39
Please see Justin's comment https://github.com/hackforla/website/issues/2901#issuecomment-1402919842 above. 
  I am awaiting decision from PM and I've created draft issue #3881 to document my suggestions for improved error detection

**Comment by roslynwythe** [comment] 2023-02-12 19:07
Closing, as the bug described in this issue was not observed.   The _wins-data.json feed appears to be correct and if changes are not reflected in the website, we believe it is because the feed is not being merged into the live site.

**Comment by roslynwythe** [comment] 2023-02-13 06:16
Closing, as the bug described in this issue was not observed. Most likely, the bug was fixed when the issue was originally closed by @luke-karis, although no detail was given. Currently, the _wins-data.json feed appears to be correct and if changes in the wins response sheet display column were not reflected in the website, it is because the feed was not being merged into the live site.

Please see https://github.com/hackforla/website/pull/3024 for details on merging wins data.

See https://github.com/hackforla/website/issues/3881 for proposed changes to provide detection of the bug, and notification in the form of a Github bug report.

**Closed as completed by roslynwythe** 2023-02-13 06:16 UTC
Labels: Bug, role: back end/devOps, Complexity: Medium, time sensitive, automation, Feature: Google Apps Scripts, size: 1pt
