### ISSUE TITLE
Fix buggy header navigation bar when resizing from desktop view to mobile view

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/website#1055] opened 2021-02-15 07:34 UTC
### Overview
The header navigation bar is buggy when resizing from desktop view to mobile view. 

The issues follow:
- [x] The header navigation bar drops down without clicking the navigation icon.  (when resizing the page from desktop view to mobile view where the viewport width is < 768 px)
- [x] The header navigation bar disappear from page (when the navigation bar is closed by clicking the X icon, and the viewport resize to >= 768px)

#### the header navigation bar drops down with navigation icon when viewport's width is less than 768px.
<img width="797" alt="Screen Shot 2021-02-14 at 9 23 32 PM" src="https://user-images.githubusercontent.com/68657634/107909488-2d49c780-6f0d-11eb-854b-47f0ce9f04e2.png">

#### the header navigation bar remains open after one click on top right navigation icon, now close icon substitutes navigation icon.
<img width="790" alt="Screen Shot 2021-02-14 at 9 23 54 PM" src="https://user-images.githubusercontent.com/68657634/107909640-7dc12500-6f0d-11eb-933a-48f39ba7a9e5.png">

#### after one click on top right X icon
<img width="790" alt="Screen Shot 2021-02-14 at 9 24 11 PM" src="https://user-images.githubusercontent.com/68657634/107909704-a77a4c00-6f0d-11eb-8e4a-8515609b0313.png">

#### header navigation disappears when resize back to >=768 px
<img width="783" alt="Screen Shot 2021-02-14 at 9 24 29 PM" src="https://user-images.githubusercontent.com/68657634/107909712-ab0dd300-6f0d-11eb-9da2-3cb98702667e.png">

### Resources
https://www.hackforla.org/about-us

**Comment by akibrhast** [comment] 2021-02-17 01:14
@drubgrubby @daniellex0 I Just want to double check with everyone if this is a bug or intended behavior? Cause the above mentioned behavior is the same across the entire site.

**Comment by jbubar** [comment] 2021-02-17 01:37
If I remember correctly, I think it is a bug that we all decided would not be worth the time to fix a while ago... but I think we are reconsidering it now.. lol

**Comment by drubgrubby** [comment] 2021-02-17 01:55
@akibrhast (@daniellex0)-  I believe it is a bug, but it's not a bug on the about-us page, it's a bug with the mobile navigation, which is on all pages.  It seems like there are two things, one is the one that Qiqi mentioned, that if you open the mobile menu, then expand the page so the regular navigation shows, and then you shrink the page again, the navigation appears already dropped down.  I think we decided that this is a minor bug, and maybe not worth fixing if that were the only problem. 

However, the larger bug is this one: 
<img width="891" alt="Screen Shot 2021-02-16 at 5 49 23 PM" src="https://user-images.githubusercontent.com/68244054/108144971-86d20380-707f-11eb-83d2-c9f192ac0da2.png">

It seems that if you open the mobile navigation, and then close it, and then expand the page, there is a point where there is no navigation at all. You may have to play around and see exactly what situation this happens in, but clearly it happens sometimes, and it's not good.

**Comment by qiqicodes** [comment] 2021-02-17 01:58
@drubgrubby Should I edit the title of this issue and address the issue as a mobile navigation issue?

**Comment by drubgrubby** [comment] 2021-02-17 02:02
@qiqicodes - That would be nice. Just remove the about-us reference.

**Comment by akibrhast** [comment] 2021-02-17 02:08
### Update
The issue starts happening when moving from 767px to 768px and then it resolves it self after 850px

### Resources
```
@media (max-width: 767px)
.main-header {
    position: fixed;
    padding: 7px;
```

```
@media (min-width: 768px)
.main-header {
    padding: 20px 10px 10px 10px;
    padding-top: 20px;
    position: fixed;
```

- https://github.com/hackforla/website/blob/8760bd1d29cf4860eebcdeb8e91fa233c550d399/_includes/main-nav.html#L1
- _includes/hamburger-nav.html

**Closed as completed** 2021-03-06 07:34 UTC
Labels: Bug, role: front end, Complexity: Medium, Feature Missing, size: missing, milestone: missing
