### ISSUE TITLE
Update the Technologies dropdown in the Projects page to match the Figma design

### ISSUE THREAD

**Issue by adam-abundis** [hackforla/website#2397] opened 2021-10-25 18:34 UTC
### Overview
We need to update the ~` Technology`~ `Languages / Technologies` dropdown menu on the Projects page to match the newly created Figma design so that we can provide a better user experience for our end-user.

### Details
With the addition of Languages into the now Languages / Technologies dropdown (formerly Technologies dropdown), this issue had to be modified to take into account the inclusion of languages in the dropdown. @IsaacDesigns from Design Team said to go ahead with implementing Version C of the desktop design and implementing the mobile design. (See https://github.com/hackforla/website/pull/2672#issuecomment-1013904367 for more info.)

<details>
  <summary><strong>Click here</strong> to see the current projects page `Languages / Technologies` dropdown on the live website for desktop and mobile(<strong>before changes</strong>)</summary>

**On desktop**  
![desktop-project-page-tech-lang-dropdown](https://user-images.githubusercontent.com/31293603/149709369-4c5c1c05-929b-4929-9988-0a24c17a9015.png)

**On mobile**
![mobile-project-page-tech-lang-dropdown](https://user-images.githubusercontent.com/31293603/149709575-81106336-2d3a-4dff-95c7-8fc6ad2ded3a.png)

</details>

<details>
  <summary><strong>Click here</strong> to see the proposed projects page `Languages / Technologies` dropdown Figma designs for desktop and mobile (<strong>after changes</strong>)</summary>

**Desktop design Version C**
<img width="446" alt="version-c-tech-lang-dropdown" src="https://user-images.githubusercontent.com/31293603/149709854-2dace92f-4341-4249-b89e-7a9eb7f77815.png">

**Mobile design**
<img width="182" alt="mobile-tech-lang-dropdown" src="https://user-images.githubusercontent.com/31293603/149709845-516e479d-b1de-4e9f-a2d6-30240a61c38b.png">

</details>

<details>
  <summary>Outdated screenshots (Do not use these)</summary>
  <details>
    <summary><strong>Click here</strong> to see the current projects page `Technologies` dropdown (<strong>before changes</strong>)</summary>
  
  ![projects-dropdown-before](https://user-images.githubusercontent.com/21162229/138750198-6fc0b04a-6bf7-4dba-a986-2d37e2611416.jpg)
  
  </details>
  
  <details>
    <summary><strong>Click here</strong> to see the proposed projects page `Technologies` dropdown Figma design (<strong>after changes</strong>)</summary>
  
  ![projects-dropdown-after](https://user-images.githubusercontent.com/21162229/138750289-838b60d3-b7b6-4e82-9480-bd710ed146df.jpg)
  </details>

</details>

### Action Items
- [x] Refactor the CSS for the desktop version of the ~` Technologies`~ `Languages / Technologies` dropdown to be 768px wide and the checkboxes create the appropriate columns to fit all technologies and languages. Also, include the scrollbar.
- [x] Ensure the dropdown matches [~Version A~ Version C of the Projects page Figma design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=15313%3A101641)
- [x] Refactor the CSS for the mobile version of the `Languages / Technologies` dropdown to include a scrollbar
- [x] Ensure the dropdown matches the [Projects page Figma design for mobile](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=15902%3A100503)
- [x] When complete, submit a pull request with the proposed changes
- [x] Make sure the page looks fine for smaller viewport screens as well, such as tablet, mobile (responsiveness)

### Resources/Instructions
- ~Version A~ Version C and mobile design within https://github.com/hackforla/website/issues/2069#issuecomment-927388942
~ [Figma- Projects page dropdown (~Version A~ Version C and mobile)](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=532%3A1454)

**Comment by anthonysim** [comment] 2021-12-18 23:34
Availability for this week:
Wed 12/23/2021: 5 - 7 PM
Fri 12/24/2021: 5 - 7 PM
Sat: 12/25/2021: 12 - 2 PM
My estimated ETA for completing this issue: Sunday 1/2/2022

**Comment by anthonysim** [comment] 2022-01-01 00:35
Progress: I haven't started as of yet. 
Blockers: 1) Where these <li> tags are generated on current-projects.html 2) how to just change technologies and not impact the other dropdowns 3) I'm thinking it might require changing the tags to <div> and using css grid?
Availability: See above comments. 
ETA: 1/8/2022
Pictures: N/A.

**Comment by SAUMILDHANKAR** [comment] 2022-01-07 02:49
Status and program areas appear switched in the after image as well as Figma. Needs to be discussed in Sunday meeting with design in case another issue is required for this.

**Comment by JessicaLucindaCheng** [comment] 2022-01-09 00:49
@anthonysim @SAUMILDHANKAR @R-Tomas-Gonzalez I noticed in the Figma all three columns are smaller and are more towards the left side. This differs from our current website. Is this a separate issue too or part of this issue?

**Comment by JessicaLucindaCheng** [comment] 2022-01-11 02:41
> @anthonysim @SAUMILDHANKAR @R-Tomas-Gonzalez I noticed in the Figma all three columns are smaller and are more towards the left side. This differs from our current website. Is this a separate issue too or part of this issue?

Bonnie says it was fine the way it is with the columns spread out for this issue.

**Comment by anthonysim** [comment] 2022-01-12 03:22
Availability for this week: 6 hours
My estimated ETA for completing this issue: Sunday 1/22/2022 

Additional technologies were added which changed the size of the dropdown. Currently waiting for/need to ask design to okay the current Version C before moving forward with adding a dropdown slide-bar for both desktop and mobile.

**Comment by JessicaLucindaCheng** [comment] 2022-01-17 05:23
Updated issue to reflect following new Version C and implementing mobile design with scrollbar. (See comment: https://github.com/hackforla/website/pull/2672#issuecomment-1013904367 for more info)

**Comment by JessicaLucindaCheng** [comment] 2022-02-04 17:51
- Availability: 6 hours
- ETA: Fri, Feb 4, 2022

**Comment by JessicaLucindaCheng** [comment] 2022-02-07 21:46
I took over this issue from the original assignee (Anthony), who has left Hack for LA. I just wanted to let you know there are differences in Anthony's implementation compared to the Figma design on the technologies/languages dropdown on the Projects page:

- For the desktop version, the height of the dropdown is 380px for tablet and desktop views, which is a shorter height than 493px that was recommended for the desktop dropdown in the Figma design. I think this was done so that the dropdown fits in a desktop or tablet view while taking into consideration the space the fixed header navigation takes up on a screen.

- In addition, the width of the dropdown was set to 718px instead of 768px for a tablet size screen. I think this was done because the width of a common tablet is 768px, which would require the width of the dropdown to be smaller than 768px.

- Also, in the Figma design for the dropdown, the font size for [each item in the dropdown is 12px](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=15313%3A101641), which makes it so the text for each item fits in one line. However, the font for each item in the dropdown for the live website is 16px, which is the minimum font size. This results in the text for some items taking up two lines and gaps in the dropdown on the live website. Here is an example of a gap:
  <img width="410" alt="tech-dropdown-gaps" src="https://user-images.githubusercontent.com/31293603/152889292-bb9aa226-7c33-4854-a408-fee7fd9a2be5.png">

  - I fixed this by having 3 columns instead of 4 so that each menu item would only need one line and no text wrapping. here is an image of the results:
  
    ![after-desktop-tech-dropdown](https://user-images.githubusercontent.com/31293603/154159942-c4df0ad8-fe69-47e8-8035-11d1cee8bbe8.jpg)
    
- Also, note that the [mobile Languages/Technologies dropdown in the Figma design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=15902%3A100503) has each menu item take up one line but the font size is 12px, which is smaller than the recommended minimum size of a 16px font. Thus, the current Languages/Technologies dropdown (even before adding the scrollbar) and the Status and Program Areas may have some menu items with text wrapping to a second line because the current font size for the dropdowns is 16px on the current website. If you want each menu item in each dropdown to be on one line, we can address that problem in a separate issue for all the dropdowns. Here is an example of the text wrapping for the Program Areas dropdown, which is similarly seen in the other 2 dropdowns in mobile: 

  ![program-areas-dropdown](https://user-images.githubusercontent.com/31293603/154163217-3f280729-7b5d-40c0-bfb0-d8dfda185517.png)

**Comment by JessicaLucindaCheng** [comment] 2022-02-09 06:41
Reopening this issue because it caused a bug as seen in issue #2754. Thus, pr #2757  
reverts pr https://github.com/hackforla/website/pull/2724 and pr https://github.com/hackforla/website/pull/2672 to fix the issue with the technologies field not being wrapped on the detail project profile page. This was caused by `id="technologies"` being used by both the Languages/Technologies dropdown and the technologies field on the detail project profile page, which should be addressed in a separate issue.

**Comment by JessicaLucindaCheng** [comment] 2022-03-12 22:57
Work on the language/technologies dropdown will continue in issue #2972 because this issue is very confusing and complicated to navigate with all the comments across the issue and prs itself, and the significant changes from the initial issue itself.

**Closed as completed by JessicaLucindaCheng** 2022-03-12 22:57 UTC
Labels: role: front end, Complexity: Large, status: Updated, Feature: Refactor CSS, P-Feature: Projects page, size: 2pt
