### ISSUE TITLE
GitHub Actions: 2 weeks inactive label bug

### ISSUE THREAD

**Issue by SAUMILDHANKAR** [hackforla/website#2634] opened 2021-12-27 09:52 UTC
### Overview
As a developer, we have to ensure that our kanban board is organized for all teams so that productivity is high. For this issue, we want the 2 weeks inactive label should be posted only after 14 days of inactivity from the time the issue is assigned.

### Action Items

- [x] Review add-label.js file located at (https://github.com/hackforla/website/tree/gh-pages/github-actions/add-update-label-weekly)
- [ ]  Add a condition which checks for the amount of time since issue was assigned, and adds a 2 weeks inactive label only if no comment or PR from the assignee.
- [ ] Release dependency on #2652 and #2032
  - [ ] Update action items in the dependency issues if needed 

### Pseudo-code

- When 14 days have elapsed from the time of issue being assigned
    - [ ] Add 2 weeks inactive label if there is no comment or PR by assignee.

### Checks

- [ ] Test in your local environment that it works
- [ ] If less than 14 days passed since issue was assigned, don't add 2 weeks inactive label.
- [ ] If less than 14 days passed since last comment by assignee, don't add 2 weeks inactive label.

### Resources/Instructions
- General info about GHAs at hack for LA website: https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions
- Specific wiki page for this GHA: https://github.com/hackforla/website/wiki/GHA:-add-update-label-weekly

**Comment by ExperimentsInHonesty** [comment] 2022-01-02 17:55
@SAUMILDHANKAR   Do we want to make sure there has not been an unassignment?

**Comment by ExperimentsInHonesty** [comment] 2022-01-02 20:42
@SAUMILDHANKAR says it will skip the loop if there is no assignee.

**Comment by JessicaLucindaCheng** [comment] 2022-04-06 21:21
@blulady 
At the time you self-assign an issue, make sure to write in a comment the following:
- Availability: "How much time will you have this week to work on this issue?"
- ETA: "When do you expect this issue to be completed?"

**Comment by blulady** [comment] 2022-04-07 00:39
Thanks Jess.
Availability: 8 hours
ETA: Wednesday 4.13.22

**Comment by lilyarj** [comment] 2022-07-05 16:54
Availability: 5hrs
ETA: 7/8

**Comment by ExperimentsInHonesty** [comment] 2022-07-06 18:28
This issue shows that summer did an update but the issue https://github.com/hackforla/website/issues/2763 still has the 2 week inactive label.  What is supposed to happen

On this issue it shows it might be adding it to soon https://github.com/hackforla/website/issues/2309

**Comment by ExperimentsInHonesty** [comment] 2022-07-06 18:30
see this page https://github.com/hackforla/website/wiki/GHA:-add-update-label-weekly
https://github.com/hackforla/website/wiki/HfLA-GitHub-Actions

**Comment by lilyarj** [comment] 2022-07-10 17:09
Progress: starting, read a bunch of material but haven't made any progress on the actual issue
Blockers: Git is acting up for me, and I am confused
Availability: 3 hours
ETA: 7/14?

**Comment by lilyarj** [comment] 2022-07-11 18:14
I'm un assigning myself from this issue, Bonnie think it might be a large issue

**Comment by ExperimentsInHonesty** [comment] 2022-09-12 21:23
@kathrynsilvaconway will review the issue and determine if its fine the way it is once a large label is added, or if it needs further clarity.  If it needs further clarity, reach out to Saumil to talk about next steps

**Comment by kathrynsilvaconway** [comment] 2022-09-13 04:00
@ExperimentsInHonesty  @SAUMILDHANKAR

I've bumped the size on this issue up to large and moved it back to the prioritzed backlog. While it is definitely more complex than we originally believed, it is straight forward enough that I still think it can be done in one issue.

**Comment by tunglinn** [comment] 2022-10-24 21:15
Availability: 6-8pm PST for the whole week
ETA: 10/26 (assuming I understand the issue, after the developer meeting)

Read through the code, not entirely sure where the bug is. Checked some issues with "2 weeks inactive" label, and it looks good.

Also, thinking ahead, I'll need to figure out how to test the action.

**Comment by blulady** [comment] 2022-10-25 01:06
@tunglinn, moving this to the in progress column.

**Comment by tunglinn** [comment] 2022-10-27 02:31
[This is what a timeline looks like.](https://api.github.com/repos/github/roadmap/issues/493/timeline)
Or you can use this format to access the timeline for any issue: https://api.github.com/repos/OWNER/REPO/issues/ISSUE_NUMBER/timeline

If there are many, many events, you can choose how many events you want to see by adding "?per_page=100" or whatever number to the end of the URL above.

Trying to find a way to test this issue without waiting 2 weeks for an issue to become inactive.

**Comment by tunglinn** [comment] 2022-11-05 03:46
Great to see the bug on this issue! github-actions added "2 weeks inactive" despite it being only 9 days.

1. Progress: I understand the code. However, I'm focusing on finding a way to test any changes.
2. Blockers: It's been a real difficulty in figuring out how to test the code. Currently trying to use [this](https://github.com/nektos/act) to use a dummy .json to test different examples of issue timelines.
3. Availability: Sat, Sun, Tuesday evening
4. ETA: 11/9

**Comment by tunglinn** [comment] 2022-11-09 01:16
Was able to test some issues in my own repository. However, in order to test in this repo, I would need an authorization token. Is this something I could have access to, or just do all the testing in my own repo?

**Comment by tunglinn** [comment] 2022-11-22 04:22
Once again, the GHA is activating before 2 weeks. Although this makes me wonder if it was designed to do so, because the action only runs once a week, so the comment is (usually) either early or late. 
Progress: I have connected the testing method to my own repo.
Blockers: Need access to a read token to test on website repo.
Availability: 5-6 hours across the week
ETA: Hopefully before next Monday

**Comment by ExperimentsInHonesty** [comment] 2022-11-27 20:42
@tunglinn @blulady I don't have any idea how to give someone a read token for the website repo or why it's needed.  Can you write something up about it, and figure out where that would live in our wiki.  See revised resources above.

**Comment by tunglinn** [comment] 2022-11-28 21:13
The problem I'm still working on is how to connect my local repo of the website to the data on GitHub. It is available freely using the "https://api.github.com/repos/OWNER/REPO/issues/ISSUE_NUMBER" format, but the documentation for the REST API requires a [token](https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28#get-an-issue). 

Using nektos act also requires a token to link the local testing to the full repository, which is required for testing this issue since it is not only checking if the assignee has commented but also if the issue is cross-referenced. The cross-referencing requires access to the whole repository and not just the issue event timeline.

**Comment by tunglinn** [comment] 2022-11-28 23:29
I have completed a testing protocol for this issue, and will update my ongoing documentation of this process.

Update on fixing the bug: I've noticed we're using the event 'cross-referenced' as an indicator of a PR linked to the issue. However, this condition doesn't check if the PR is from the current assignee. For example in issue #2395, this GHA is detecting the last PR from a previous user.

**Comment by tunglinn** [comment] 2022-12-08 21:07
List of bugs that need to be fixed:
- [x] Detecting linked PRs from non-assignees
- [ ] Triggering early

**Comment by tunglinn** [comment] 2022-12-26 05:36
1. Progress: I found bugs, now I need to fix them without changing the logic too much.
2. Blockers: Shaky internet access until the new year.
3. Availability: Jan 2-5
4. ETA: Jan 5

**Comment by tunglinn** [comment] 2023-01-08 18:07
1. Need to figure out what examples to give PR reviewers to test the code.
2. No blockers
3. 10-11 am on weekdays.
4. Friday

**Comment by tunglinn** [comment] 2023-01-09 18:44
1. One thing I noticed about using the classic vs fine-grain token is that when I use fine-grain, events that should be labeled as "cross-referenced" are retrieved as "mentioned". 

Therefore, if testing this issue, make sure to be using a classic token.

2. There are several method to solve this bug. All of them require some sort of refactoring. I'll be attending office hours this week to ask if this is allowed.

**Comment by ExperimentsInHonesty** [comment] 2023-02-07 01:35
@tunglinn Hope you are doing well.  Can you provide an update on this issue, or move it back to the prioritized backlog if you are unable to continue.

**Comment by tunglinn** [comment] 2023-02-10 07:59
Having trouble finding time to work on this. I wouldn't mind sending it back to prioritized backlog, but I would prefer if I handed this off to someone else who can finish it ASAP, in which I could explain how to fix this issue.

**Comment by jdingeman** [comment] 2023-02-27 20:39
Hi @tunglinn, just sent you a message via Slack. Putting this here as well.

Please provide us with a write up or a video recording of your attempts at resolving this issue, and what approaches you found that worked/didn't work and what the next dev working on this issue will need to look out for.

Thanks!

**Closed as completed** 2023-03-05 02:28 UTC
Labels: Bug, role: back end/devOps, Complexity: Large, time sensitive, status: Updated, Feature: Board/GitHub Maintenance, size: 3pt
