### ISSUE TITLE
Workflow Run Set PR labels not adding labels to Pull Requests

### ISSUE THREAD

**Issue by SAUMILDHANKAR** [hackforla/website#2933] opened 2022-03-05 22:31 UTC
### Overview
As a developer, I want all my workflow runs to be successful. For this issue, we will identify and fix the error which causes the [Workflow Run Set PR labels](https://github.com/hackforla/website/actions/workflows/wr-set-pr-labels.yaml) to fail.

### Details
[Workflow Run Set PR labels](https://github.com/hackforla/website/actions/workflows/wr-set-pr-labels.yaml) is not adding labels to some of the pull requests. We need to fix this bug so that the labels from the issue can be added to their linked pull requests automatically.

### Action Items
- [x] Review [set pr labels yml file](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/set-pr-labels.yaml) and [set pr label js](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-pr/set-pr-labels.js) 
- [x] Identify why some PRs such as https://github.com/hackforla/website/pull/2918, https://github.com/hackforla/website/pull/2899, https://github.com/hackforla/website/pull/2969 didn't get the label from their linked issue. (For these issues, the labels on PRs had to be added manually, see [comment1](https://github.com/hackforla/website/pull/2918#issuecomment-1057496142) and [comment2](https://github.com/hackforla/website/pull/2969#issuecomment-1065682110))
- [ ] Replicate the scenario in your own repo, make the code changes and ensure that labels are added on all pull requests automatically.
- [ ] Make sure existing functionalities are not impacted by this code change.
- [ ] Finally, make a pull request to fix the issue.

### Resources/Instructions
[set pr labels yml file](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/set-pr-labels.yaml)
[set pr label js file](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-pr/set-pr-labels.js)
Related prs where this issue was encountered: https://github.com/hackforla/website/pull/2918, https://github.com/hackforla/website/pull/2899, https://github.com/hackforla/website/pull/2969
Sample workflow failure: https://github.com/hackforla/website/actions/runs/1904313617

**Comment by tunglinn** [comment] 2022-07-01 02:19
Availability: 6 hours/Friday, Sunday, Monday 
ETA: 7/4/2022

**Comment by tunglinn** [comment] 2022-07-04 17:39
Progress: Understanding how Github actions work, duplicated repo into a private repo for testing.
Blockers: Unable to test actions in private repo.
Availability: M-Th (6 hours/each)
ETA: 7/11

**Comment by tunglinn** [comment] 2022-07-06 19:18
I'm unable to access the action logs from the mentioned PRs (log retention is capped at 90 days for public repositories). 
Overall, I found that PR label workflow fails to trigger along with the pull request instructions. I believe that the issue is not solely in the PR label workflow.

Here's a more detailed report of the mentioned issues:

For https://github.com/hackforla/website/pull/2918, PR label and PR request instruction workflow wasn't run on the creation of the PR. 
PR label was run on two other occasions:
<details>
<summary>on a commit (b4ae447) that comes from a different PR that the user reviewed</summary>

![image](https://user-images.githubusercontent.com/86996158/177630185-6238d666-2e35-4d22-a3d3-dd504e295bd5.png)
</details>

<details>
<summary>when someone removed a label and edited PR</summary>

![image](https://user-images.githubusercontent.com/86996158/177629639-ab859ae4-1d2c-4fc7-88fc-29c9aaec94fc.png)

![image](https://user-images.githubusercontent.com/86996158/177629689-6ec099a9-ab10-4c4c-b647-1826893f0919.png)
</details>

Next, https://github.com/hackforla/website/pull/2899 is not a true failure example. My understanding is the user manually added the labels during the creation of the PR <details> <summary> because the labels are added by the user before the Add Pull Request Instructions comment.
</summary>

![image](https://user-images.githubusercontent.com/86996158/177630906-ecc32382-170f-4158-8550-15698f0da965.png)

![image](https://user-images.githubusercontent.com/86996158/177631114-0e35bae9-41bd-4964-8724-292935e5ff64.png)

</details>
<details><summary> and the PR labels workflow did trigger. </summary>

![image](https://user-images.githubusercontent.com/86996158/177631358-8dbe1644-7d95-427e-a2ff-8ccee69aeadc.png)

</details>


Finally, for https://github.com/hackforla/website/pull/2969, it looks like both the PR labels and PR request instructions workflow did not trigger if you check the "Checks" tab in the PR. 

<details> <summary>This is under the "Checks" tab of the issue.</summary>

![image](https://user-images.githubusercontent.com/86996158/177652142-163dcf38-fa24-4ad9-a347-a8370ed4efcc.png)
</details>


Patterns found:
<details><summary>For both 2918 and 2969, there was a different user in an earlier commit. I will look into other PRs with similar commit histories.</summary>

![image](https://user-images.githubusercontent.com/86996158/177634375-4e99553e-b6bd-45dc-88b3-eba431adb1d7.png)

> and 

![image](https://user-images.githubusercontent.com/86996158/177634455-5d12d4c6-7bf5-4cab-a169-f0537e879fc9.png)

</details>
<details><summary> None of the workflows triggered when PR was opened even though it should have according to this code. </summary>

> from pr-instruction.yml

![image](https://user-images.githubusercontent.com/86996158/178576642-b586b842-f895-4481-992e-1b415f367078.png)
> from set-pr-labels.yml

![image](https://user-images.githubusercontent.com/86996158/178576738-7f858aa0-ee48-434d-841c-3886077aa517.png)
</details>

I found some recent PRs where github-actions did not add labels.

[7/6/2022](https://github.com/hackforla/website/pull/3332) - when PR was created, did not link issue
[7/5/2022](https://github.com/hackforla/website/pull/3329) - looks like the user manually added labels during PR creation, so not true failure
[6/30/2022](https://github.com/hackforla/website/pull/3326) - looks like the user manually added labels during PR creation, so not true failure

**Comment by tunglinn** [comment] 2022-07-06 21:22
Found https://github.com/hackforla/website/pull/3318, where a commit from a different user is added into the PR.
<details><summary>triggered both PR labels and PR request instructions workflow</summary>

![image](https://user-images.githubusercontent.com/86996158/177645355-ac50e7a3-1b78-47e1-a01b-52c3366f502a.png)
</details>
<details><summary>PR labels are good, but the PR request instructions comment doesn't exist</summary>

![image](https://user-images.githubusercontent.com/86996158/177645453-4aad940e-bf80-45c4-8414-ce3891f28d18.png)
</details>

Lint SCSS is always triggered on pull requests being synchronized. One potential solution is to add `synchronize` to the types of events that triggers the PR labels and request instruction workflow.

Next steps will be recreating and testing in private repository.

**Comment by tunglinn** [comment] 2022-07-07 18:10
Found a few PR with same issue with logs still intact! 
https://github.com/hackforla/website/pull/3087 - false alarm, it seems like none of the workflow ran because there was a merge conflict of some sort merge conflict that Jessica mentioned.
<details><summary> Workflows don't run if there is a merge conflict </summary>

![image](https://user-images.githubusercontent.com/86996158/177847566-29ca5df3-9c0c-4dae-a23f-660c7189e4e2.png)
</details>

https://github.com/hackforla/website/pull/3116 - false alarm, the merge branch isn't correct, workflows do not run unless they are for gh-pages, feature-homepage-launch, or feature-tech-dropdown

**Comment by tunglinn** [comment] 2022-07-07 18:29
Hi all, 
I'd like to test workflows on https://github.com/hackforla/website/pull/2969. 
I'd like to remove a label, and then edit the PR to trigger the workflow. Bonnie and I discussed this and seems harmless. Also, there is some precedent as Saumil did it in https://github.com/hackforla/website/pull/2918.
Please let me know if this will cause problems.

**Comment by tunglinn** [comment] 2022-07-12 01:11
Did some testing in existing PRs. I removed a label, updated the top PR comment, which should trigger the PR label workflow to re-add the label.

<details><summary>When testing in an already merged pull request #3291, the PR label action is able to be triggered.</summary>

![image](https://user-images.githubusercontent.com/86996158/178377883-9ffb7564-28d6-445a-b0e4-416343d2335d.png)
</details>

<details><summary>However #2969 and #2918 did not trigger the PR label action.</summary>

![image](https://user-images.githubusercontent.com/86996158/178377955-d452ca31-4f0d-4885-9a8c-5c1a0d012176.png)


![image](https://user-images.githubusercontent.com/86996158/178386423-f4e17b50-34bc-4fc1-88cf-334674a2caeb.png)

</details>

<details><summary>I tested #2905, a PR from the same time as the two above. The workflow did trigger. </summary>

![image](https://user-images.githubusercontent.com/86996158/178393358-000abbd1-9d44-45d3-bf02-37f978283e26.png)

</details>

I thought that the workflow only triggers if the branch the PR is pulling from still exists.
<details><summary> But #2970 has a deleted branch, yet it triggers PR label action.</summary>

![image](https://user-images.githubusercontent.com/86996158/178402199-d465dd7a-819d-4536-aa20-96a3388c60ce.png)
</details>

<details><summary>#2943 doesn't trigger. The from branch is greyed out, which is different from deleted branches in which you can click but brings you to a 404 error page. </summary>

![image](https://user-images.githubusercontent.com/86996158/178566143-ac916ad5-0472-4167-8e2c-e15897f98228.png)
</details>

**Comment by JessicaLucindaCheng** [comment] 2022-07-13 00:44
@tunglinn I noticed this pr doesn't have labels on it and has `Fixes #3316` so the automation should have put labels on it. The pr is #3340

**Comment by tunglinn** [comment] 2022-07-13 00:59
@JessicaLucindaCheng I think it's because there's a merge conflict. I mentioned a case similar to this in this comment https://github.com/hackforla/website/issues/2933#issuecomment-1178023100. Do we want it to run even if there's a merge conflict?

Another piece of evidence is that Lint SCSS didn't run either.

**Comment by tunglinn** [comment] 2022-07-13 19:55
I've been unable to replicate the bug. 

Is it possible that it was a bug on the server side (GHA)? 
https://www.githubstatus.com/ mentions some degraded performance around the time of the PRs with this bug.

**Comment by tunglinn** [comment] 2022-07-16 04:58
Team has decided to close this issue and write up a decision report.

[Decision report](https://github.com/hackforla/website/wiki/DR:-Squashing-PR-GitHub-Actions-bug,-not-adding-labels-or-instructions) has my findings and recommended steps to take if the bug does appear again.

**Closed as completed by tunglinn** 2022-07-16 04:58 UTC
Labels: Bug, Status: Urgent, role: back end/devOps, Complexity: Medium, status: Updated, Feature: Board/GitHub Maintenance, automation, size: 1pt
