### ISSUE TITLE
Fix broken link to "Contribute to Docs" in website-wiki homepage

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#6142] opened 2024-01-22 10:30 UTC
### Overview
Fix the broken link to "Contribute to Docs" on the website-wiki homepage at index.md

### Details
- The live wiki website is https://hackforla.github.io/website-wiki/
- The homepage link "Contribute to Docs" is supposed to display README.md but the link is broken

### Action Items
- [ ] browse to https://github.com/hackforla/website-wiki and create fork
- [ ] from the `hackforla` folder, run
```
git clone https://github.com/<your_GitHub_user_name>/website-wiki.git
```
- [ ] open new workspace in VS Code, for the website-wiki folder
- [ ] create issue branch off `main`
- [ ] Edit the file docs/index.md to fix the "Contribute to Docs" link to README.md
- [ ] To pull the docker image, run 
```
docker pull vraer/hfla-website-wiki:latest
```
- [ ] To start the development server
```
docker run --rm -it -p 8000:8000 -v ${PWD}:/docs vraer/hfla-website-wiki:latest
```
error:
```
rosly@DESKTOP-IP18TPE MINGW64 ~/hfla/website-wiki (update-README)
$ docker run --rm -it -p 8000:8000 -v ${PWD}:/docs vraer/hfla-website-wiki:latest
the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'
```

### Resources/Instructions
REPLACE THIS TEXT - Provide links to resources or instructions that may help with this issue. This can include files to be worked on, external sites with solutions, documentation, etc.

**Comment by roslynwythe** [comment] 2024-01-22 10:46
- see PR in hackforla/website-wiki:  https://github.com/hackforla/website-wiki/pull/13

**Comment by JessicaLucindaCheng** [comment] 2024-01-23 01:46
@roslynwythe
- Is this a duplicate of https://github.com/hackforla/website/issues/4364? If yes, decide on which duplicate issue you want to close.

**Comment by ExperimentsInHonesty** [comment] 2024-02-29 23:47
This issue has been resolved (not sure how, but it looks like it's going to the correct page https://github.com/hackforla/website-wiki/blob/main/README.md

**Closed as completed by ExperimentsInHonesty** 2024-02-29 23:47 UTC
Labels: role: front end, Feature: Wiki, Complexity: Small, size: 0.5pt, Draft
