### ISSUE TITLE
Refactoring: Multiple if else statements in add-label.js to be combined into functions

### ISSUE THREAD

**Issue by SAUMILDHANKAR** [hackforla/website#2652] opened 2022-01-02 10:32 UTC
### Dependency
- [x] #2634 

### Overview
For this issue, we need to refactor multiple if else statements in [add-label.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-schedule/add-update-label-weekly/add-label.js) file so that our code quality and efficiency improves.

### Action Items

- [x] Review add-label.js file located at (https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-schedule/add-update-label-weekly/)
- [ ]  Refactor [multiple if else statements](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-schedule/add-update-label-weekly/add-label.js) such that they can be combined into functions
- [ ] Check to see if wiki page for this GHA needs to be updated to reflect your changes

### Checks
- [ ] Test in your local environment that it works
- [ ] Make sure all the functionalities in [add-label.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/add-update-label-weekly/add-label.js) file still work fine

### Resources
- File where changes need to be made: [add-label.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/add-update-label-weekly/add-label.js)
- [Hack for LA's WIKI page for add-update-label-weekly](https://github.com/hackforla/website/wiki/GHA:-add-update-label-weekly)
- Hack for LA's [GitHub Actions Wiki](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions)

**Comment by jdingeman** [comment] 2023-03-09 03:43
Ready for prioritization

**Comment by angieyan** [comment] 2023-03-27 18:14
Availability: Mar 27 11:00 AM - 1 PM, Mar 31 2PM - 3PM, Apr 2 9AM - 10AM
ETA: Apr 2, by 10 AM

**Comment by angieyan** [comment] 2023-04-03 21:47
Dear @hackforla/website-merge team, I noticed that the link provided in the Action Items section is no longer available. The .js file has been moved to the following folder: website/github-actions/trigger-schedule/add-update-label-weekly, and it looks different than it did before. I have also discussed this issue with @bzzz-coding, who had worked on it previously. Please let me know what my next steps should be regarding this issue.

**Comment by bzzz-coding** [comment] 2023-04-05 19:25
@angieyan and @hackforla/website-merge In my opinion, the issue is likely obsolete because the current code looks quite different from the code linked in the issue. A few weeks ago, I worked on debugging this GHA and the bug was in the isTimelineOutdated function mentioned in this issue, and to fix the bug, I had to refactor the function (I was not aware of this issue). The code in this file could be further refactored but I doubt if refactoring the isTimelineOutdated function is needed or should be a priority.

**Comment by jdingeman** [comment] 2023-04-11 23:34
@angieyan @bzzz-coding - there are still several if/else statements that could be refactored if possible. In particular, lines 158 - 194 have many verbose if/else statements. Is it possible to refactor these to be more efficient? Or is this the result of your refactoring @bzzz-coding ?

**Comment by bzzz-coding** [comment] 2023-04-11 23:50
I intentionally added some nested if/elseif statements between line 178-194 to trigger detailed console logging for easier debugging/reviewing and code maintenance in the future so to me, this function makes sense. That being said, this function is HUGE 😅 so I understand if @angieyan and @jdingeman you think further refactoring is needed and would make the code easier to read and to reason about.

**Comment by angieyan** [comment] 2023-04-12 00:49
@jdingeman - Lines 158-165 could definitely be refactored. If we don't need the console logging statements added intentionally by @bzzz-coding between lines 168-194, then I can also refactor those lines. Just guide me on which variation would be better. In my opinion, the logging statements really help.

**Comment by jdingeman** [comment] 2023-04-25 02:14
Hi @angieyan - we discussed this and we are going to close this issue as not planned but still have you assigned. We definitely appreciate the work. 
While we work on putting out back-end medium issues, would you be able to check out this issue:
- https://github.com/hackforla/website/issues/2032
Basically you could just assign yourself to this issue (even though it is in New Issue Approval), and determine if this issue is still actually relevant to our operation. If it is, then you can work on the fix. If it is not, then you can close the issue as not planned with a note about why it is no longer relevant. 

Thanks! 😄

**Closed as not planned by jdingeman** 2023-04-25 02:14 UTC
Labels: status: Help Wanted, role: back end/devOps, Complexity: Medium, status: To Update!, Feature: Refactor JS / Liquid, Feature: Refactor GHA, size: 1pt, Lang: GHA
