### ISSUE TITLE
Increase ratio of image on project page for Railstats LA to 3:2

### ISSUE THREAD

**Issue by shaswa** [hackforla/website#1150] opened 2021-03-02 23:36 UTC
### Overview
All  project images on the [hackforla homepage projects section](https://www.hackforla.org/#projects) should have a 3:2 ratio and a standard resolution of 600x400. 

Current Resolution: 2000 x 2000 pixels
Current Ratio: 1:1

### Action Items

UX Design
- [x] Increase ratio of project image for Railstats LA  to 3:2
- [x] Update Status on #1105 and add new image to the comment

Front-End Development
- [x] Add new resized image to Railstats project card (scroll to bottom of this issue for final image)

### Resources/Instructions
[Projects page](https://www.hackforla.org/#projects)
[Image](https://www.hackforla.org/assets/images/projects/metro-ontime.png)

**Comment by ExperimentsInHonesty** [comment] 2021-03-17 18:56
Basicly you take the logo and create a white canvas that is 600x400 and then move the logo onto it reducing its size.

**Comment by shinhope** [comment] 2021-04-01 01:46
![RailstatsLA image 600x400](https://user-images.githubusercontent.com/79497980/113232047-44d8d780-9251-11eb-91d8-8676ed04b134.png)

**Comment by shinhope** [comment] 2021-04-01 01:47
![RailstatsLA image 1](https://user-images.githubusercontent.com/79497980/113232179-7ce01a80-9251-11eb-9fc3-1d34ed866f6d.png)

**Comment by shinhope** [comment] 2021-04-01 01:50
![RailstatsLA image2](https://user-images.githubusercontent.com/79497980/113232435-f7a93580-9251-11eb-881d-05e5458a7bb4.png)

**Comment by daniellex0** [comment] 2021-04-08 16:58
@shinhope Can you please add a new image with the railstats logo vertical (straight up) and white space on both sides of it to fill the space? (still with the dimensions above). Please add the new version here. Thanks you!

**Comment by shinhope** [comment] 2021-04-08 17:57
![Railstats vertical](https://user-images.githubusercontent.com/79497980/114074375-27ab9680-9859-11eb-8a1c-ac0583050573.png)

**Comment by daniellex0** [comment] 2021-04-08 19:59
Looks good, thanks @shinhope ! Moving this to development

**Comment by RobertaFricker** [comment] 2021-04-21 00:22
(I removed the images due to their size as I'm using the image posted by shinhope 12 days ago)
@shinhope 
@daniellex0 
@shaswa 
@Oluwafemi-Jegede 
I resized the original image of 2000 x 2000 using Photo in Windows 10.   I used this app because it retains the transparency where Paint does not.  (For now, please disregard the black background, it's just a display issue with Photo app.)
Below is a copy of the original image and the resized image with their related sizes indicated.
Before I change the original, please confirm this is what you would like:

ORIGINAL 2000 X 2000
(removed by me)
RESIZED 600 X 400
(removed by me)

Thanks!

**Comment by daniellex0** [comment] 2021-04-21 00:44
Hey @RobertaFricker I think you can actually just use the image that @shinhope posted in her comment above - is there an issue with that one? Sorry if this wasn't clear, the resizing part of this issue was already done by design- now it just needs to be added to the site by development

**Comment by daniellex0** [comment] 2021-04-21 00:44
The image in this comment: https://github.com/hackforla/website/issues/1150#issuecomment-816023698

**Closed as completed** 2021-04-22 16:13 UTC
Labels: good first issue, role: front end, P-Feature: Project Info and Page, time sensitive, size: missing
