### ISSUE TITLE
Organizing updates to site into branches

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#121] opened 2019-05-27 23:15 UTC
## Overview

Discussion about using branches to store approved pull requests, until we are ready to push a version update or pushing each version to gh-pages, as we are now, but then retroactively assigning version tag.

## Action Item
Discussion

**Comment by thekaveman** [comment] 2019-05-28 16:42
Please see my comments in #120 and #122 regarding when/how tags/versions are created. 

Note that just because a commit is merged into `gh-pages`, it does not necessarily mean you have to tag/release. It's OK to stack a few up. It's also OK (as you suggest here) to create e.g. a `dev` branch that collects all related PRs for a new tag/release until ready. This is typical in larger software projects, I don't know that we need the complexity on this site now - and without a staging/preview version, it isn't as useful. (That could be the next task, to setup previews using e.g. surge.sh or something).

**Comment by thekaveman** [comment] 2019-05-28 16:51
I'm actually going to close this as a duplicate of the earlier #97.

**Closed as completed by thekaveman** 2019-05-28 16:51 UTC
Labels: Discussion, Feature: Administrative, Research, role: infrastructure, Ignore: Duplicate
