### ISSUE TITLE
Add the Heart.png image back

### ISSUE THREAD

**Issue by jbubar** [hackforla/website#1062] opened 2021-02-17 01:31 UTC
### Overview
For some reason in [this pr](https://github.com/hackforla/website/pull/1007), we accidentally deleted the heart.png image.. please add it back.

### Action Items
- [ ] Take the following image, and add it to the assets/images/projects folder. 
- [ ] title it heart.png
![heart](https://user-images.githubusercontent.com/53061723/108143344-66547a00-707c-11eb-8db2-9da4f1e273d3.png)
- [ ] check the project page locally to see if the image is displayed on the project

### Resources/Instructions
[hfla site where you can see that the heart image is missing](https://www.hackforla.org/?status=Completed)

**Comment by akibrhast** [comment] 2021-02-17 15:18
Duplicate of #1050

**Closed as completed by akibrhast** 2021-02-17 15:18 UTC
Labels: Bug, good first issue, role: front end, time sensitive, Ignore: Duplicate
