### ISSUE TITLE
Look at installing a CMS to be able to update project card information without code

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#228] opened 2019-12-25 02:39 UTC
### Overview
It would be nice if we had a way for predictable changes to the project cards, to be managed without it becoming a coding task.

The changes that have come up in the past two weeks that could have been managed by this are: 

- Removing a partner from a project card (food oasis)
- Changing the status on a project card from On Hold to Active (tdm-calculator)
- Adding a project card to a website (undebate).  

### Action items
Discuss the option of using netlifyCMS (you don't have to use netlify to use it), as a tool for having a CMS to manage the website content (on the project pages and on cards.  

 

Additionally, We have an opportunity to build a template website for neighborhood councils, to push various tools onto (311, undebate, etc), but it would need a cms, so that lay people could edit the content.  I understand how our website works, so thought we could talk about it using the above context, since then I will be able to understand your analysis easily.

### Resources
[NetlifyCMS public repository](https://github.com/netlify/netlify-cms)
[Instructions for installing it without using Netflify permanently](https://cnly.github.io/2018/04/14/just-3-steps-adding-netlify-cms-to-existing-github-pages-site-within-10-minutes.html ) - its a little circuitous but still only takes 10 min, according to this article.

**Comment by ExperimentsInHonesty** [comment] 2020-01-26 18:19
Cynthia's update is that it's going to work great.  May not be appropriate for website, but possibly 311 project.  
1. Progress
2. Blocks
3. Availability
4. ETA

**Comment by ExperimentsInHonesty** [comment] 2020-02-02 19:00
Cnythia will meet with Steven on Monday to learn about the github integration and github actions.

**Comment by ExperimentsInHonesty** [comment] 2020-02-09 18:15
The progress report for this is:

1. Progress - non last week
2. Blocks - redirected to another project
3. Availability - NA
4. ETA - 3/1/2020

**Comment by cnk** [comment] 2020-03-15 06:18
I think Open Authoring is what we want: https://www.netlifycms.org/docs/open-authoring/ 
Starting to work on it here: https://github.com/cnk/website/tree/netlify

And these guys have fabulous docs about how to use GitHub or Netlify to edit their docs: https://axway-open-docs.netlify.com/docs/contribution_guidelines/#option-2-edit-on-netlify-cms We should shamelessly adapt those for our wiki once this method of editing is available.

**Comment by yulia-kh** [comment] 2020-04-02 05:20
Cynthia and I tested editing of the existing projects and it seems to work in the desired way. With proper instruction it should be very straightforward and as mentioned before can be managed without it becoming a coding task.
The current block is that incoming data schema a little different from the config file.
The next step is to figure out if we should (can?) change the config.yml to match our existing data OR if we are better off changing what the project card expects to get for its display.

**Comment by ExperimentsInHonesty** [comment] 2020-04-05 17:32
Show team the publiccode.yml pusher

**Comment by yulia-kh** [comment] 2020-04-19 16:59
Here's example of netlify-cms connected to the website https://yulia-kh.github.io/testing-netlify/admin/. Repo link https://github.com/yulia-kh/testing-netlify

**Comment by cnk** [comment] 2020-04-19 17:50
Fantastic demo! 
Next steps: 

- [x] Look into options for validating data as it is entered (link name options, text lengths, etc) to prevent people entering data we won't want to approve
- [x] Improve help text for each field (e.g. define differences between Site, Test Site, Demo Site link types)
- [x] Can we format the preview pane on the right of the edit form? (ideally incorporate the project page styles or at least format as the project.md file yml indentation)
- [ ] Experiment with what the user experience is if the pull request needs editing before being approved
- [ ] Experiment with what the user experience is if the pull request needs to be returned to the requester for more substantial changes. Can we return the requester to the NetlifyCMS edit form via a deep link?

**Comment by yulia-kh** [comment] 2020-04-26 16:24
Summary:
 - There is a built in way to do a basic form validation through regex pattern. This allows us to check length of the input or check for specific values. 

@ExperimentsInHonesty, @cnk  It made me think what exactly do we want to check? Possible things to consider: length of the description field (min and max), allowed link names (Site, Demo, Test Site, Slack, GitHub, Readme), anything else? 

 - We can use hints for every input field. Do we have requirements/standards for our project cards and pages? Possible thing to consider: difference between Site, Demo Site, Test Site; length of description, example input.

 - According to Netlify CMS I can format the preview pane on the right of the edit form with a link to css file. But it doesn't seem to work for me. I'm exploring this issue.

Other blocks:
 - Preview links don't work (it's another way to demonstrate changes on the go)
 - I started to get `Failed to persist entry: API_ERROR: Reference already exists` for entries that were edited before. I'm working on finding the way to reproduce this behavior, because now it's inconsistent. I'm not clear on what leads to it.

Still need to explore:
 - User experience with pull requests that need editing

**Comment by yulia-kh** [comment] 2020-05-03 17:19
User experience with pull requests is as follows.

- When a user save changes  `view preview` link shows up. Preview shows a page with changes, but doesn't apply style like bold text or heading even though these options provided (adds # or ** instead like in markdown)
- When user sets status to `In review` - pull request is created
- When a user sets status to `Draft` again - pull request is closed by a user
- When admin closes pull request it goes back to drafts but a user can't see admin's comments
- When admin request changes on github a user doesn't see anything in the account (github sends notification to email)

**Comment by ashlingam** [comment] 2020-05-10 17:29
After consideration, the team decided to abandon this implementation due to unresolved technical issues. Dev will pursue a different approach.

**Closed as completed by ashlingam** 2020-05-10 17:29 UTC
Labels: role: infrastructure, role: back end/devOps, Feature Missing, size: missing, Complexity: Missing, milestone: missing
