### ISSUE TITLE
Tailor GHA message to improve workflow and individual responsibility when creating issues

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/website#2127] opened 2021-08-18 06:17 UTC
### Overview
As a developer, I want to have the messages posted by the GHA-bot to motivate proper behavior to ensure a smooth team workflow. For this issue, we need to tailor the message that an issue creator will see when one or more feature, role, or size labels are missing upon new issue creation.

#### Product

- [x] Review the message from [add-labels-template.md](https://github.com/hackforla/website/blob/gh-pages/github-actions/issue-labels/add-labels-template.md) and [no-labels-template.md](https://github.com/hackforla/website/blob/gh-pages/github-actions/issue-labels/no-labels-template.md), to ensure that it is optimal, and motivates the right behavior.
- [ ] If the message is fine, this issue can be closed.
- [x] If not, post a new message in the comments below with the new message. Be sure to label them so that we can tell which new message is for which file.
- [ ] Replace the 'role:product' label with 'role: backend' if the below items are needed. Else, close the issue.

#### Developer

- [x] Locate the new messages posted by the PM team, and edit them as necessary in the md files noted below.

### Resources/Instructions
[no-labels-template.md](https://github.com/hackforla/website/blob/gh-pages/github-actions/issue-labels/no-labels-template.md)
[add-labels-template.md](https://github.com/hackforla/website/blob/gh-pages/github-actions/issue-labels/add-labels-template.md)

Currently, the message from `no-labels-template.md` is displayed when an issue is created with all the required labels. However, the `add-labels-template.md` is unused because the message might not be optimal. Specifically, the current message would motivate adding the missing labels, even if the issue creator does not have the prerequisite expertise to do so (for ex, a developer might improperly add labels for a design issue). Also, since this message pops up when an issue is created, should we leverage this message to include, maybe, other items the issue creator needs to review besides labels (for example, checking that their overview or action items are well formed).

**Comment by ExperimentsInHonesty** [comment] 2021-09-05 16:16
@Aveline-art please add size and re-add "ready for milestone" label

**Comment by ExperimentsInHonesty** [comment] 2021-09-08 20:21
@Aveline-art @abuna1985 @matthewlee626 This message is not current.

It show up even when they have not added labels and the issue is moved automatically now to the New Issue Approval column when its added to the board

```
Good job adding the required labels to this issue.

Just a friendly reminder to also move the issue into the "New Issue Approval" column under the Project Board. For more info on that, check Github's documentation here. Thanks!``

Product would be happy to take a look at a new draft when you have one.
```
Moving this back to new issue approval for re writing of action items

**Comment by macho-catt** [comment] 2021-09-08 20:28
@ExperimentsInHonesty is there an example issue where the author did not add labels and the post showed up (when it shouldn't)? That way I can troubleshoot. 

As for the second line of the post, we can make an issue to remove that or update this issue to remove that.

Thanks

**Comment by ExperimentsInHonesty** [comment] 2021-09-08 23:06
@macho-catt What needs to happen is that someone needs to model what happens when you do each of the things below and see where it does not make any sense.  This does not need anyone from product to do this, this can be done by front end or back end leads or merge team or anyone who has been around long enough to understand how issues work.

Here is the stuff I would model to see what does not work the way we intend.
1. What happens when you make an issue and don't add any labels.
2. What happens if you make an issue and add 1 label.
3. What happens if you make an issue and add all the required labels (size, feature, role)

put the ready for milestone label on this again when you are ready for me to sign off on the issue

**Comment by Aveline-art** [comment] 2021-09-10 17:49
@ExperimentsInHonesty I am not sure what exactly is being asked of us. Would you like us to create some chart or graphic that clears up what the flow of the GHA is?

**Comment by macho-catt** [comment] 2021-09-26 16:39
We can discuss this workflow during one of the dev meetings (either Tue or Thu) and get feedback from developers to see which makes sense. 
Currently, it works like this:

1. If I create an issue and I don't add any labels:
    - the three labels for "missing" will be added: "size missing", "feature missing", "role missing"
2. If I create an issue with only one of the required labels (for example, size: medium):
    - the two other labels for "missing" will be added: "feature missing", "role missing"
3. If I create an issue and add all required labels:
    - The bot does not add any labels and posts a comment telling the user they added the proper labels. 
    - The comment previously mentions the project board, but since that is now automated it has been removed
    - The comment also links to wiki articles for issue creation and labels, but those wiki articles have been postponed

Other things that will need to be brought up with devs:
1. There is currently an unused message (the code is commented) for when a user forgets to add the proper labels. Due to a discussion with @Aveline-art, we decided to remove it for now. The requirements may have changed now so we can discuss to use this code again.
2.  The current used message for point 3 was initially made because the project board was not automated. Now that it's just text for congratulating the user + links to unfinished wiki articles, is it still relevant? Can we put other things in it?
3. There is a a fun race condition where if a user creates an issue without any of the proper labels, it will trigger the action. However, if during the time the action is triggering the user adds the proper labels, the github action will remove the labels the user just added and put the three missing labels. The problem: when the github action triggers, the API will only look at the issue's metadata during the creation; it won't look at the metadata of the issue after it's created.

**Comment by macho-catt** [comment] 2021-11-03 22:23
Two new issues need to be created so this can be closed:
1. ~~Issue to update no-labels-template.md so that the message given by the bot is up to date with how the current issue creation workflow is~~ the message is already updated so this is done
2. Issue to update add-labels-tempate.md so that the bot creates a message if labels are missing.

**Comment by macho-catt** [comment] 2021-12-10 18:48
Will finish this issue this week (by Sunday)
Availability: 2 hours

**Closed as completed** 2021-12-12 22:31 UTC
Labels: role: back end/devOps, status: Updated, Feature: Board/GitHub Maintenance, Complexity: Small, size: missing
