### ISSUE TITLE
Update Project Profile: Home Unite Us

### ISSUE THREAD

**Issue by ghost** [hackforla/website#3772] opened 2022-12-20 21:38 UTC
### Project Name

Home Unite Us

### Project Card URL

home-unite-us.md

### Update the Title?

NO

### Update the Description?

NO

### Update the Image?

NO

### Update the Technologies?

NO

### Update the Partner(s)?

NO

### Update the Tools?

NO

### Update GitHub Link?

NO

### Update Slack Link?

NO

### Update Test Site Link?

NO

### Update Demo Site Link?

NO

### Update Site Link?

NO

### Remove person(s) and info from Leadership?

YES

### If YES on remove person(s), edit the below to provide the information required. If NO, delete the template in the field below:

Name: Tracy Michelle
Name: Regan Hutson
Name: Kristy Points
Name: Ben Ross

### Add person(s) and info to Leadership?

YES

### If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:

Name: Jed Stewart
GitHub Handle: jed-stewart
Role: Developer
Slack Member ID: U04A3J6V0HY

Name: Mira Kinebuchi
GitHub Handle: mira-kine
Role: Developer
Slack Member ID: U0411CAL13N

Name: Stephen Barkley-Yeung
GitHub Handle: stevbark
Role: Developer
Slack Member ID: U041403GHEC

Name: Kristelle Gumaru
GitHub Handle: K-Gumarama
Role: Product Manager
Slack Member ID: U031VJ99ATU

Name: Sanya Nijhawan
GitHub Handle: sanya301
Role: Product Manager
Slack Member ID: U031FLYS561

Name: Raji Pradheap
GitHub Handle: rpradheap
Role: Product Manager
Slack Member ID: U02R9MKA6KH

Name: Bryce Lednar
GitHub Handle: brycelednar
Role: Product Manager
Slack Member ID: U049TSDG2SX

Name: Farah Khan
GitHub Handle: fourmatte
Role: UX/UI Designer
Slack Member ID: U01JC8VEKMH

Name: Eduardo De La Rosa
GitHub Handle: edela0015
Role: UX/UI Designer
Slack Member ID: U0430G2T4AC

Name: Flora Osmond
GitHub Handle: itzflowa
Role: UX/UI Designer
Slack Member ID: U047ZT4GP5E

### Project Status

Active

### Update your meeting times?

NO

**Comment by randelbrot** [comment] 2022-12-20 21:48
duplicate of 3773

**Closed as not planned** 2022-12-20 21:58 UTC
Labels: role: front end, role: back end/devOps, P-Feature: Project Info and Page, time sensitive, Complexity: Small, size: 0.5pt
