### ISSUE TITLE
Record Clearance project update

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#826] opened 2020-12-05 00:24 UTC
### Overview 
We need to update the record clearance team display to reflect the current team members

### Action Items
- [x] List each team member
   - [x] Name
   - [x] role
   - [x] Github handle
   - [x] slack member id
- [x] indicate anyone to remove

### Resources
https://www.hackforla.org/projects/record-clearance-project

**Comment by j100892** [comment] 2020-12-05 01:18
**Name:** Daniel Lee 
**Role:** Project Lead & Product Manager 
**Github Handle:** j100892
**Slack Member ID:** U01BU7LQFHB

**Name:** Daniel Xiao 
**Role** Tech Lead
**Github handle:** aahvocado 
**Slack Member ID:** U01CQR12PA8

Need to Remove: Kelsey Justis, Angelina Molina, Wesley Rowe 

**Meeting Times are now:** 9:30 - 10:00 PM PST 

**Updated Information:**: 

The Record Clearance Project aims to help people in California with criminal records accomplish record clearance, expungement or reduction and subsequently a second chance as a part of society. 

We work with verifiable non-profits, the government and partners to build digital tools that can affect changes in the lives of these justice impacted individuals.

**Comment by abenipa3** [comment] 2020-12-22 23:16
Hello everyone,  quick updates:

- I updated the organization with the new information.
- Removed Kelsey Justis, Angelina Molina, Wesley Rowe.
- Added Daniel Lee and Daniel Xiao.

I just need to update the meeting times but will push what I have so far to my repo so we could discuss it in tonight's meeting.

Thank you!

**Comment by abenipa3** [comment] 2020-12-23 03:17
@j100892 May you please confirm if the meeting day is on Monday?

After this confirmation, we would like to reach out to VRMS (@Rankazze @ExperimentsInHonesty ) to change the meeting times to 9:30 - 10:00 PM PST on the confirmed day.

**Comment by j100892** [comment] 2020-12-23 03:25
@alyssabenipayo Hey! Sorry for not updating this in the ticket but our meeting times have changed and I haven't had the the chance to let VRMS know. Here are the new times: 

We currently have three meetings: 

Dev meetings Thurs. @ 6 PM PST - 7PM PST   // Design & Research meetings Tues.  @ 6 PM PST - 7 PM PST  // Team meetings Biweekly Mon. @ 6 PM PST - 7 PM PST

**Comment by abenipa3** [comment] 2020-12-27 00:50
@j100892 Hello! Thank you for updating us with the new meeting times.

@Rankazze @ExperimentsInHonesty May we please update the meeting times for Record Clearance to the following? Thank you.

Dev meetings Thurs. @ 6 PM PST - 7PM PST
Design & Research meetings Tues. @ 6 PM PST - 7 PM PST
Team meetings Biweekly Mon. @ 6 PM PST - 7 PM PST

**Comment by drubgrubby** [comment] 2021-03-15 20:13
@alyssabenipayo - These meeting times have been changed.  Can you please confirm that they are correct on the website?  If there is nothing else on this ticket then, I suppose, you can close it.

**Comment by abenipa3** [comment] 2021-03-15 22:25
@j100892 The meeting times for [Record Clearance](https://www.hackforla.org/projects/record-clearance-project) have been updated. May you please confirm if they are correct?
![image](https://user-images.githubusercontent.com/38295612/111229115-93744980-85a2-11eb-8ddd-fd9aa27af79f.png)

**Comment by akibrhast** [comment] 2021-04-04 23:24
@drubgrubby @alyssabenipayo What is the next step here? Can we close this? Is there a PR?

**Comment by abenipa3** [comment] 2021-04-04 23:28
@akibrhast No PR. The meetings are correct based on what @j100892 provided [earlier](https://github.com/hackforla/website/issues/826#issuecomment-749906319), but because the update was back in December - I wanted to confirm with him again to see if the meeting times are still correct so that we can close the issue. 

@drubgrubby  Should we proceed to close the issue or wait for confirmation?

**Comment by drubgrubby** [comment] 2021-04-04 23:48
@alyssabenipayo go ahead and close this. If the meeting times change again they can just open a new ticket at VRMS.

**Closed as completed** 2021-04-04 23:49 UTC
Labels: good first issue, Status: Urgent, role: front end, P-Feature: Project Info and Page, size: missing
