### ISSUE TITLE
Fix Language Display 

### ISSUE THREAD

**Issue by ahdithebomb** [hackforla/website#831] opened 2020-12-06 18:54 UTC
### Overview 

We need to figure out what is wrong with the script that pulls the language files from each GitHub project repository and displays on site. 

### Action Items 

- [ ] Read the Wiki to identify how the script is supposed to work.
- [ ] Check the functionality of the script. 
- [ ] Identify what is causing the blockage/breakage.
- [ ] Prescribe fix.
- [ ] Review with the team.
- [ ] Make the updates.   

### Resources 
https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture

**Comment by KianBadie** [comment] 2020-12-06 19:36
@ExperimentsInHonesty the languages are back on the site.

The cause of the error was that when I rewrote the github actions data fetching script in pull request #757, I made the mistake of saving language data to the [github-data.json](https://github.com/hackforla/website/blob/gh-pages/_data/github-data.json) file without the `data` field. I stored the languages as `languages: [language1, language2, language3, ...]`, instead of the original `languages: { data: [language1, language2, language3, ...] }`. This broke the way the projects page accessed the langauges data (as they were trying to reference the original `languages.data`).

I merged pull request #832 that now displays the languages on the home pages. It's a tempfix, as I will double check some things. I'm not sure if that format change I described above broke other things (like if other sources depend on the original `languages.data` reference), or if having the `data` field is preferred. If not, then the solution I merged should be good :+1: I did this for now just to at least have the languages up in the meantime.

**Comment by KianBadie** [comment] 2020-12-18 05:14
Sorry for the lack of activity. I have been much busier with work the past week and a half, and have been using my free time to just do something non code related. The deadline for my work project is this Monday, which is when I can continue activity on this.

**Comment by KianBadie** [comment] 2020-12-27 18:00
I double checked the things I mentioned in the above comments. It seems like the current fix works perfectly fine and no other places in the project depend on the old way of referencing the languages data. The only reason I would see changing the structure back is to keep consistency between the different data sets (as contributors data is accessed by `<Contributors Data Set>.data` as opposed to accessing languages data through just `languages`). I'm not sure if the "data" property is necessary in the contributors data sets or if the "data" property should be added back to the languages data set. But for the purpose of displaying the language data data and removing the bug this issue is referencing, things are fixed.

**Comment by KianBadie** [comment] 2021-01-08 02:11
I currently have a branch that reverts things to the old way "`languages.data` instead of just `languages`" which keeps keeps the structure of the data similar to the contributors data set. Like I mentioned earlier, I'm not sure if  the `data` property is necessary, since all these data sets just have one property (which is the `data` property). But I think that topic is outside this issue (sorry if this is such a minor point to elaborate on. In the end, this is all sort of for convention I think rather than actuall changes to how the website looks).

@ExperimentsInHonesty (sorry if you are the wrong person to ping) If you would want the branch I described in this comment to be merged (it changes like 4 lines of code), then let me know! If not, I think this issue is fine to close, unless you want me to write anything more for documentation purposes. Either option will close this issue :+1:

**Comment by ExperimentsInHonesty** [comment] 2021-02-04 00:16
@drubgrubby @jbubar can you both look at this issue and after discussion figure out next steps.

**Comment by pawan92** [comment] 2021-02-14 18:08
This will be looked at in the break out rooms

**Comment by jbubar** [comment] 2021-02-14 19:36
I will look at this and contact kian before the dev meeting on tuesday

**Comment by jbubar** [comment] 2021-02-17 06:28
I think this issue is good to close. Thanks Kian!

**Closed as completed by jbubar** 2021-02-17 06:28 UTC
Labels: Bug, role: back end/devOps, Feature Missing, size: missing, Complexity: Missing, milestone: missing
