### ISSUE TITLE
Add Program Area: HelloGov

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#2382] opened 2021-10-20 21:09 UTC
### Overview
We need to add program area information to the HelloGov project so that it will show up when we add the program areas filter.

### Action Items
- [x] Review the project.md file model in the Resources section
- [x] Add the following text to the file indicated in the Resources section
```
program-area:  
    - Vote / Representation
```

### Resources/Instructions
File location to make the change: _projects/hellogov.md

URL for UAT to check the page has been changed: https://github.com/hackforla/website/blob/gh-pages/_projects/hellogov.md

[Model for project.md files](https://github.com/hackforla/website/wiki/project.md-file-template)

**Comment by SAUMILDHANKAR** [comment] 2021-12-21 01:03
@jnmrles: Just wanted to share a point from our Sunday team meeting. We are now requesting all developers to add eta and availability at the time of picking up an issue or when you are assigned to an issue. Just wanted to let you know. Thank you.

**Comment by jnmrles** [comment] 2021-12-29 01:33
Progress: It seems that the needed updates for this issue are already made prior to assigning it to myself. Should I close this?

**Comment by SAUMILDHANKAR** [comment] 2021-12-30 02:50
@jnmrles: Thanks for checking this. Yes. looks like needed updates are already there.
@ExperimentsInHonesty: I have confirmed the HelloGov project is showing up when we add the program areas filter. It is also being reflected in the [hellogov.md file](https://github.com/hackforla/website/blob/gh-pages/_projects/hellogov.md). So, I am closing this issue.

**Closed as completed by SAUMILDHANKAR** 2021-12-30 02:50 UTC
Labels: good first issue, role: front end, role: back end/devOps, P-Feature: Project Info and Page, size: missing
