### ISSUE TITLE
Revise Contact Us form to new section

### ISSUE THREAD

**Issue by cnk** [hackforla/website#384] opened 2020-03-22 17:14 UTC
### Overview
Submitting the contact form at the bottom of http://hackforla.org goes to a thank-you page with a 405 status. When fixing this form, also see if the same or similar issue affected the form that was replaced by the getting started button.

The new Contact Us section will include buttons for Volunteer, Non-Profit, Government, and Other. The Volunteers button will link to the HFLA Slack channel. The Non-Profit and Government buttons will link to their corresponding surveys. The Other button will link to a new Other Survey.

### Action Items
- [x] Remove Contact Us form
- [x] Create Other survey
- [ ] Create Contact Us section wireframe
- [ ] Implement Contact Us section with appropriate links

**Comment by ExperimentsInHonesty** [comment] 2020-04-05 18:15
@leonelRos 
1. Progress - played with it
2. Blocks availability last week
3. Availability: Today
4. ETA: tomorrow

**Comment by ExperimentsInHonesty** [comment] 2020-04-19 18:01
@leonelRos and @cnk to work on it today.

**Comment by leonelRos** [comment] 2020-04-19 21:31
@ExperimentsInHonesty . @cnk  @yulia-kh  and I got the contact us form to work. Now, if we can get access to Action Network so I can work with both ends and check if they are successfully receiving the message and email from the form and implement custom fields. so we can separate real people from trolls.

**Comment by wesrowe** [comment] 2020-04-25 22:43
@harishlingam @cnk @ExperimentsInHonesty – i just caught up with @leonelRos about the state of the contact us section/form. 
I want to shout out props to @cnk and @leonelRos for investigating this form; for years everyone assumed it actually "contacted" someone, and we didn't realize the issues below.

Product observations: 
 - _the form never worked as intended._ Even if it had been sending the user's message text (it wasn't), there was not mechanism set up in Action Network to notify anyone about it. (I will research this further and edit here if I learn something)
 - from a membership-development perspective, we should talk about whether it makes sense to instead leverage AN's robust form and segmentation tools instead of a "send us a message". we should be able to embed a form that, for example, lets someone indicate their interest areas along with their email.
 - removing the "subscribe" form, and instead driving everyone to the Get Started button, may be missing a segment of our visitors who would prefer to get newsletters rather than join a project.
 - there doesn't seem to be any validation of user email addresses, which means that people aren't confirming their opt-in. i'm pretty sure that we need to do this to comply with the law. (so we should do what other newsletters do: send a "confirm email"/opt-in email.

Suggestions:
 - Leo's suggestion (i agree) is to replace the contact us form with a subscribe form; possibly an embedded AN form if we can make that work.
 - implement email confirmation and newsletter opt-in

Hopefully we can discuss in the team meeting 4/26

**Comment by ashlingam** [comment] 2020-04-26 20:24
1. Progress - Harish to create Other survey and wireframe of section. Will discuss with Bonnie afterward.
2. Blocks - None
3. Availability - Sunday, Monday, Saturday
4. ETA - 4/29

**Comment by harishlingam** [comment] 2020-04-26 23:40
1. Progress
2. Blocks - None
3. Availability - Sunday, Monday, Saturday
4. ETA - 4/29

**Comment by leonelRos** [comment] 2020-04-26 23:51
@harishlingam  @ExperimentsInHonesty are you guys ok if I hide the contact us form that we have on the website until we come up with a new one. I am ready to make that pull request!!

**Comment by ashlingam** [comment] 2020-04-27 00:34
@leonelRos We've decided to create an entirely new Contact Us section, which I'm now working on. I do not think we will be using the Contact Us form at all. I think hiding it is fine for now. Can you include a comment in the code explaining the forthcoming revision?

**Comment by leonelRos** [comment] 2020-04-27 00:48
perfect1 Will do.

**Comment by wesrowe** [comment] 2020-04-27 01:51
@harishlingam @leonelRos Note that there is a Contact Us main menu item, so actually removing CU could have a few annoying side effects. CU is also a really expected feature on a website. 
Alternatives to hiding the section:
1. swap in the old commented-out "subscribe to newsletter" code from the top of the page.
2. add a button (not a form) with a simple mailto: link, that opens the visitor's email client and addresses an email to something like team@hackforla.org (i think that's the right email).
3. steer people to Slack
4. or all 3?
It would be easy to implement, you just need a little copy and follow the style guide you already have (with Yuiko's input of course).

**Comment by ashlingam** [comment] 2020-04-27 02:17
Hi @wesrowe I discussed a new structure to the Contact Us section with @ExperimentsInHonesty . The Contact Us menu item would not be removed. However, we will remove the Contact Us form at the bottom and replace with 4 buttons, each for Volunteer, Non-Profit, Government, and Other. 

The Volunteer button will link to the Slack channel and the other 3 buttons will link to their respective survey pages (which we are creating). I imagine a Subscribe to newsletter button could also be included here, perhaps at the top above the 4 aforementioned buttons.

I am wireframing this concept and will share here for further input.

**Comment by wesrowe** [comment] 2020-04-27 03:19
@harishlingam @ExperimentsInHonesty, my suggestion was a minimal approach for the interim/very short term, a patch for the visitor experience that Leo could bang out quickly. I'm happy to hear you're already working on the more permanent approach.

**Comment by cnk** [comment] 2020-05-01 04:56
@leonelRos I merged the pull request commenting out the contact form but there is still a link to it in the top navigation. Up to whether to remove it for now - or press on with adding the 4 buttons.

**Comment by leonelRos** [comment] 2020-05-01 05:03
@cnk  I forgot about that. I check the link and It doesn't redirect to the contact us form. However, I am going to comment it out as well since we are working on a new one

**Comment by leonelRos** [comment] 2020-05-02 00:33
@cnk @ExperimentsInHonesty  @harishlingam  the "Contact us" link in the main nav has been hidden. I check every other link on the page and everything works accordingly. Looking forward to implementing the new form. 

<img width="1185" alt="Screen Shot 2020-05-01 at 5 32 27 PM" src="https://user-images.githubusercontent.com/50648001/80850621-bd628e80-8bd1-11ea-934b-b2bbbdaff3e6.png">

**Comment by ashlingam** [comment] 2020-05-02 20:16
Thanks for the update @leonelRos. I am working on a prototype for the new section and will share with the group once complete. We may reintroduce the Contact us link or replace with a Get in Touch link at that point.

Prototype of revised home page: https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=352%3A205

**Comment by ashlingam** [comment] 2020-05-03 23:43
The buttons as shown on the screen shot will link to pages as follows:

Get Started -> [Getting Started Page](https://www.hackforla.org/getting-started)
Government -> [Government Survey](https://docs.google.com/forms/d/e/1FAIpQLSfxe8Os2nAd8TJ__qPDgWoxuzZ_SAQ0kQGGDlnlNvGRqL5ppA/viewform)
Non-Profit -> [Non-Profit Survey](https://docs.google.com/forms/d/e/1FAIpQLSfZWLHCQ_dCSiGC9b6ykZIRrnrw_2XZJ8HyOV6mFDbepGxGxA/viewform)
Other -> [Other Survey](https://docs.google.com/forms/d/e/1FAIpQLSfITZOU9EESlm65gRpl9itbNql4PdLKxnc6sFwlHGdgLw2EFg/viewform)

<img width="584" alt="Screen Shot 2020-05-03 at 6 42 17 PM" src="https://user-images.githubusercontent.com/21990572/80928963-fdf70f00-8d6d-11ea-9b54-126a554e91cf.png">

**Comment by wesrowe** [comment] 2020-05-04 15:54
@harishlingam This split sends a very specific signal to the visitor that we're looking to hear from gov't or nonprofits, and everyone else is "other" -- which seems a little off-key from the rest of the site being aimed at individuals. I'm not sure if you're planning any difference in functionality between how the three groups would be handled (gov, nonprofit, other), but if splitting is necessary then at the least could we make sure the list feels inclusive? A more user-friendly segmentation might be "organization" vs "individual."

**Comment by ExperimentsInHonesty** [comment] 2020-05-05 21:30
@wesrowe the reason we have other is because we expect all individual needs to be addressed by the getting started link.  But we felt we needed catchall for anyone who was not either a potential partner or a volunteer.  So based on your feedback could change it to Other Partner.  What language next to the button would suggest?

**Comment by wesrowe** [comment] 2020-05-05 21:42
@ExperimentsInHonesty Do the different buttons actually do different things? The differentiation of some groups is what's creating this need to actually name the "not them" group -- which will ultimately not feel very inviting to the not-them group, no matter what word you put there.

**Closed as completed** 2020-05-11 14:10 UTC
Labels: good first issue, role: front end, Feature Missing, size: missing, milestone: missing
