### ISSUE TITLE
Refactor JS: Move script from wins.html to an external js file

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/website#2231] opened 2021-09-08 01:31 UTC
### Overview
As a member of the website development team, Javascript code is much more maintainable and reusable if they exist in a separate folder rather than embedded with html. For this issue we will be moving the files in [wins.html](https://github.com/hackforla/website/blob/gh-pages/pages/wins/wins.html).

### Action Items
- [ ] Review the notes below to understand recent changes to our architecture
- [ ] Move code in the above noted file to an appropriately named file in an appropriate folder in our js folder.
- [ ] Delete the code from the above noted file
- [ ] Make sure that the website still runs and that the wins page still looks the same.

### Resources/Instructions
[assets/js](https://github.com/hackforla/website/tree/gh-pages/assets/js)
[wins.html](https://github.com/hackforla/website/blob/gh-pages/pages/wins/wins.html)

#### Architecture Notes

The idea behind the refactor is to get all of our website's JS code into an organized, consolidated state. Currently, we want our JS files to exist in our [assets/js ](https://github.com/hackforla/website/tree/gh-pages/assets/js)directory with these specifications:

- In the main js directory, the js files should ideally have names corresponding to a related .html page (for example, updates.js should connect to updates.html).
- In the elements sub-directory, the js fjiles should correspond to code needed for our [design system elements ](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)to function.
- In the utility sub-directory, the js files represent reusable code that can be used in multiple files. If any js code is reused, they belong in utility, and called in a separate file in the main directory.

That said, this structure is not set in stone. If any part of it feels strange, or you have questions, feel free to bring it up with the team so we can evolve this format!

**Comment by macho-catt** [comment] 2021-11-16 04:58
This is a duplicate of #2116, so I'm closing this

**Closed as completed by macho-catt** 2021-11-16 04:58 UTC
Labels: role: front end, Complexity: Medium, Feature: Refactor JS / Liquid, size: missing
