### ISSUE TITLE
Update Project Profile: VRMS

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#286] opened 2020-01-27 22:43 UTC
### Overview
Provide collateral for the HackforLA website

### Action Items
- [ ] Gather items
     - [ ] 600 x 400 image
          - [ ] Alt image text
     - [ ] Hero image to be displayed on Project Home Page at 1500 x 700 px
          - [ ] Alt image text
     - [ ] Name of project
     - [ ] A blurb about your project
     - [ ] Links (website, GitHub, etc.)
     - [ ] What you are looking for skill-wise
     - [ ] Partner(s)
     - [ ] Location
     - [ ] Readme
- [ ] Add project card to website

### Resources/Instructions
See project cards on the hackforla.org website for examples

**Comment by ExperimentsInHonesty** [comment] 2020-03-02 03:47
Duplicate of Issue #288

**Closed as completed by ExperimentsInHonesty** 2020-03-02 03:47 UTC
Labels: Status: Urgent, documentation, P-Feature: Project Info and Page, size: missing, Complexity: Missing, role missing
