### ISSUE TITLE
Epic: Rename events passed as a function parameter to e 

### ISSUE THREAD

**Issue by StephenTheDev1001** [hackforla/website#5290] opened 2023-08-23 06:32 UTC
### Dependency

- [x] #5291
- [x] #5292 
- [x] #5293 
- [x] #5300 
- [x] #5301
- [x] #5302
- [x] #5303
- [x] #5304
- [x] #5305
- [x] #5306
- [x] #5307

### Overview

Rename events passed as a function parameter to `e` to have consistency throughout the JS files

### Action Items

- [ ] Find all events passed in as a function parameter that is not named `e`. Make issues that rename the parameter to `e` and renames everywhere that parameter is used within the function to `e`.

### Resources/Instructions

Use this [Template](https://github.com/hackforla/website/issues/new?assignees=&labels=Feature%3A+Refactor+HTML%2C+good+first+issue%2C+ready+for+dev+lead%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+size%3A+0.25pt&template=img-tag-refactor-on-website.md&title=img+Tag+Refactor%3A+%5BINSERT+PAGE+HERE%5D+page%28s%29) as a guide for creating the issues.

**Comment by StephenTheDev1001** [comment] 2023-08-23 06:48
I found about six more cases like this and thought it would be a good set of first issues

**Comment by ombhagwani** [comment] 2023-08-23 06:55
assign me this Issue , im working on it.

**Comment by StephenTheDev1001** [comment] 2023-08-23 07:08
@ombhagwani25 attend the onboarding first https://www.meetup.com/hackforla/events/289632860/
https://www.hackforla.org/getting-started

**Comment by StephenTheDev1001** [comment] 2023-08-23 07:34
@roslynwythe You asked for ideas for "good first issues". I only found about 6 cases. Please look this and it's dependencies over, and suggest improvements, so I can continue with the other dependencies.

**Comment by ombhagwani** [comment] 2023-08-23 13:48
sorry I just randomly came over here to contribute in open source. I apologize for my inappropriate behavior.

**Comment by StephenTheDev1001** [comment] 2023-08-24 01:49
@ombhagwani25 Hack For LA is very welcoming imo, I highly recommend attend the onboarding to see if this organization is for you.

**Comment by roslynwythe** [comment] 2023-08-27 16:35
@StephenTheDev1001 This is a great idea and the issue is well written.  My only concern is whether they are all appropriate for `good first issues`, since the testing of some of the pages is not trivial.   I put `Ready for Prioritization` on the two issues that target `About Us` page, since that page is easier to test.  For the others I wonder if we can give some guidance for testing, or should we make them Complexity: Small?

**Comment by StephenTheDev1001** [comment] 2023-08-29 00:01
@roslynwythe complexity:small is probably the way to go, maybe even medium. I would need to do a good amount of research on how to test some of those js pages to write a guide. Would labeling them a higher complexity and have the assignee/reviewers figure out the testing be enough? Should I add a testing Action Item to the more difficult ones to test?

**Comment by roslynwythe** [comment] 2023-08-29 08:15
PM did not wish to pursue, closing as not planned.

**Closed as not planned by roslynwythe** 2023-08-29 08:15 UTC
Labels: role: front end, role: back end/devOps, Complexity: Medium, Feature: Refactor JS / Liquid, size: 1pt, Issue Making: Level 2, Complexity: See issue making label
