### ISSUE TITLE
Project Card Issue Updates - Public Tree Map

### ISSUE THREAD

**Issue by IAgbaje** [hackforla/website#869] opened 2020-12-24 18:20 UTC
### Overview

We need to create an issue for each project to funnel any updates they have to the website team 

### Action Items 
- [ ] Get updates from the following 2 projects   
    - [ ] Public Tree Map

#### Action Items per Project 
- [ ] Create an issue using [Project Profile Card review and update Issue Template](https://github.com/hackforla/website/issues/new?assignees=&labels=Role%3A+Product+Management%2C+Feature+-+Project+Info+and+Page&template=project-profile-card-review-and-update.md&title=Update+Project+Profile%3A+%5BProject+Name%5D)
- [ ] Initial Reach out to Project  
    - [ ] Go to each individual project page on the HfLA website to locate the name/slack handle of the respective product manager 
     - [ ] Reach out to the Product Manager via slack in their project channel to notify them that their project card needs to be updated

![Screen Shot 2020-12-22 at 1 47 46 PM](https://user-images.githubusercontent.com/44422322/102936084-547b9f80-445c-11eb-8c29-4ec5387e4738.png)

  - [ ] Follow up until we can get the necessary updates 
     - [ ] Check in again on the channel after 2 days (" Is __________ still the project PM?" 
     - [ ] Attend their next team meeting

### Resources/Instructions
- [Project Profile Card review and update Issue Template](https://github.com/hackforla/website/issues/new?assignees=&labels=Role%3A+Product+Management%2C+Feature+-+Project+Info+and+Page&template=project-profile-card-review-and-update.md&title=Update+Project+Profile%3A+%5BProject+Name%5D)
- [Example](https://github.com/hackforla/website/issues/857)
- [Hack for LA Projects](https://www.hackforla.org/#projects)

**Comment by pawan92** [comment] 2021-01-10 21:04
This is a duplicate of #889

**Closed as completed** 2021-01-10 21:04 UTC
Labels: role: product, P-Feature: Project Info and Page, size: missing, Complexity: Missing
