### ISSUE TITLE
Communities of Practice information updates: Engineering

### ISSUE THREAD

**Issue by mxajPrice** [hackforla/website#5132] opened 2023-08-03 02:19 UTC
### Remove person(s) and info from CoP file?

NO

### If YES on remove person(s) edit the below to provide the information required. If NO, delete the template in the field below:

Name:

### Add person(s) and info to CoP file?

NO

### If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:

Name:
Title:
GitHub Handle:
Slack Member ID:

**Comment by mxajPrice** [comment] 2023-08-03 02:20
This template does not have a space for it, but the meeting times on [this page](https://www.hackforla.org/communities-of-practice) need to be updated to 6pm PT Thursdays.

**Comment by JessicaLucindaCheng** [comment] 2023-08-05 01:09
@mxajPrice 
- There is already an open issue for the meeting time to be updated to `Thursdays 6:00-7:00 pm PT`. It's in issue #5003.

**Comment by JessicaLucindaCheng** [comment] 2023-08-05 01:50
@hackforla/website-pm 
1) Since this issue is already addressed in #5003, can this issue be closed with a comment, "This is a duplicate of #5003" and adding an `Ignore: Duplicate` label?
2) AJ said, "This template does not have a space for it..." and another issue (#5131) also requested a meeting time update. Should the _Communities of Practice information updates_ issue template be updated or should development find a way for the Communities of Practice meeting times to be updated automatically to match the meeting time on the [Events page](https://www.hackforla.org/events/)?

**Comment by ExperimentsInHonesty** [comment] 2023-08-06 16:40
@JessicaLucindaCheng We need an ER to 
- start pulling the meeting time from the VRMS data
   - add a note to the CoP update form that meeting changes need to be made in VRMS (dependent on the prior line)

After the ER is made this issue can be closed with the existing notes.  No need to mark it as ignore.

**Comment by JessicaLucindaCheng** [comment] 2023-08-28 21:54
> @JessicaLucindaCheng We need an ER to
> 
> * start pulling the meeting time from the VRMS data
>   
>   * add a note to the CoP update form that meeting changes need to be made in VRMS (dependent on the prior line)
> 
> After the ER is made this issue can be closed with the existing notes. No need to mark it as ignore.

- The #5328 has been created.

**Closed as completed by JessicaLucindaCheng** 2023-08-28 21:54 UTC
Labels: good first issue, role: product, time sensitive, P-Feature: Communities of Practice, ready for dev lead, size: 0.25pt
