### ISSUE TITLE
Clean wins.html 

### ISSUE THREAD

**Issue by Abel-Zambrano** [hackforla/website#1981] opened 2021-07-20 01:19 UTC
### Overview
Clean code on wins.html

Converting Array of Arrays (rawData) into an array of objects with {key: value} pair to remove unnecessary hard coded keys and clean the file.

### Action Items

- [ ] Convert the rawData array (line 87) into an array of objects with {key: value} to replace hardcoded keys in the wins.html file (lines 31-62).
- [ ] Remove code/notes from lines 28-62 and assure the page works as normal and nothing breaks.

### Resources/Instructions

[wins.html](https://github.com/hackforla/website/blob/gh-pages/pages/wins/wins.html)
[How To: Convert an Array into an Object](https://stackoverflow.com/questions/4215737/convert-array-to-object)

IMPORTANT!!
This issue is working off of a feature branch!
Please follow this wiki before creating a new branch!
[how to work off a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)

**Comment by Aveline-art** [comment] 2021-08-07 00:54
@Abel-Zambrano Please tell me more about what this issue is about in the overview. Why is this something that needs to be done? Who does this edit serve? In what what?

**Comment by Abel-Zambrano** [comment] 2021-08-07 01:28
@Aveline-art This issue was actually discovered by @jbubar. I don't know the in-depth details of the issue. Hopefully he's still available and can provide more details.

**Comment by Abel-Zambrano** [comment] 2021-08-07 01:34
@Aveline-art I believe the idea was to convert the Google App Script array into an object with {key: value} to replace hardcoded keys in the wins.html file, lines 31-44

**Comment by Aveline-art** [comment] 2021-08-10 18:22
@Abel-Zambrano Can you add this information to the action items so that this can be worked on by the team? Thank you!

**Comment by Abel-Zambrano** [comment] 2021-08-11 16:33
@Aveline-art All done.

**Comment by Aveline-art** [comment] 2021-08-11 19:02
@Abel-Zambrano I will also need more information on the overview and the resources to understand what the issue is about. What is the purpose of this issue? What need does this address for the team? What exactly is the context behind this task?

**Comment by Abel-Zambrano** [comment] 2021-08-12 02:41
@Aveline-art I apologize, I had the wrong page referenced, it's the wins.html page. I updated the issue and provided more details. The purpose is to essentially clean the page and provide cleaner code for anyone working on that file.

**Comment by jbubar** [comment] 2021-08-20 05:20
Closing issue and rewriting it. Sorry @Abel-Zambrano and everyone if this was a headache. you are doing great

**Closed as completed by jbubar** 2021-08-20 05:20 UTC
Labels: role: front end, Complexity: Medium, P-Feature: Wins Page, size: missing, Feature: Feature Branch
