### ISSUE TITLE
Identify which pages call Tools data from each project

### ISSUE THREAD

**Issue by Sebster3** [hackforla/website#4525] opened 2023-04-16 21:23 UTC
### Overview
To ensure consistency with surrounding data, we need to update the formatting of `tools` in each project's frontmatter to a YAML array. To safely propagate this change, we must identify which pages reference the `tools` frontmatter data in each project's markdown file in the `_projects` folder.

### Details
We're going to format the `tools` data like the `technologies` data, so that we can reuse some existing code. To do this safely, we need to identify which files need updating.

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside many of the markdown files in the `_projects` folder and find the `tools` variable. As an example, [access-the-data.md](https://github.com/hackforla/website/blob/gh-pages/_projects/access-the-data.md) includes `tools` in its frontmatter.
- [x] Identify which pages make a reference to, or otherwise query, the `tools` data stored in the project files, and then trace to the base file with the logic for displaying the data. Examples include but are not limited to:
    - [x] [Projects Page](https://github.com/hackforla/website/blob/gh-pages/pages/projects-page.html) and related files:  
      - [current-projects.html](https://github.com/hackforla/website/blob/gh-pages/_includes/current-projects.html)
      - [current-projects.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js)
    - [x] [Projects Check Page](https://github.com/hackforla/website/blob/gh-pages/pages/projects-check.html) and related files
      - [current-projects-check.html](https://github.com/hackforla/website/blob/gh-pages/_includes/current-projects-check.html)
      - [current-projects-check.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects-check.js)     
    - [x] [project.html](https://github.com/hackforla/website/blob/gh-pages/_layouts/project.html) page- used in individual project pages
- [x] Document your findings in a Google Doc in the "HackForLA.org" Google Drive
	- [x] Document how those pages and related file(s) make use of the `tools` data.
	- [x] Document the effects to the current pages when the `tools` data is saved as a yml list, then
	- [x] Document the necessary changes that must be made to each page and the related file(s) to ensure that the current implementation and rendering are not broken when the formatting of the data changes. 
	      *This will require careful analysis of the current code which uses the `tools` data to ensure it does not break when provided an array of data instead of a single string.*     
	- [x] Link the Doc in the **Resources/Instructions** section below.	    
- [x] Discuss your findings with the dev lead(s) and PM(s).

For Merge Team/Tech Leads/PMs:
- [x] When this issue is complete, release the dependency on #4776, move that issue from "Ice Box" to "New Issue Approval", and add `ready for dev lead` label.

### Resources/Instructions
- [Markdown Frontmatter](https://jekyllrb.com/docs/front-matter/)
- Project files: [`_projects`](https://github.com/hackforla/website/tree/gh-pages/_projects)
- [x] Add link here to the document identifying each page that: uses the Tools data, and what changes need to be made

**Comment by jdingeman** [comment] 2023-04-30 03:32
Hey @Sebster3, nice job on writing the issue. I would say just include a statement in the overview a brief reason _why_ we need to do this, just to contextualize it. 

Could you clarify this item

>  Document if any changes should be made for each page to maintain current functionality when reformatting tools as a YAML array.

I think I understand what you're saying but it's a bit unclear why the dev will need to do this.

**Comment by Sebster3** [comment] 2023-05-02 21:46
Thanks for the feedback @jdingeman! I made the requested changes.

Is the amount of information given on the 4th action item sufficient, or would it benefit from providing a more structured way to document any changes that are necessary? If so, is there a preferred way to document this sort of information? (such as indicating the affected function names or line numbers)

As far as finishing the issue from the dev's perspective, is there guidance I should provide for where this final documentation should end up (e.g. a PDF saved in Google Drive), or is that better left for the dev to sort out?

**Comment by roslynwythe** [comment] 2023-05-10 07:06
Hi @Sebster3 I think this looks good.  The last two Action Items could be something like:
- [ ] Write up a report in a Google Doc in the "HackforLA.org website" Google Drive and add a link to it in the Resources/Instructions section below.  
- [ ] Review your report with dev lead(s) and PM(s).  Discuss the plan for making the transition.  For instance, can all changes be made in a single issue and if so, what Complexity issue?

It might be useful to mention that the plan is to format `tools` in a manner similar to `technologies`, so we might be able to reuse some code that is used to process the technologies array (if that makes sense).

**Comment by Sebster3** [comment] 2023-05-11 20:10
Thanks for the help, @roslynwythe. I believe the issue is ready to go, pending approval.

**Comment by ExperimentsInHonesty** [comment] 2023-05-14 18:51
- @hackforla/website-merge can you all review this and add a ready for prioritization label.  its holding up a bunch of other issues.  As soon as this issue is done it can release #4427 which in turn releases another issue, which releases another issue, and then leads to the creation of a bunch of new small issues.

**Comment by t-will-gillis** [comment] 2023-05-17 21:13
- @ExperimentsInHonesty I did a final review and made some minor edits, then I hid most of the comments as you suggested. I believe it is ready.

**Comment by ExperimentsInHonesty** [comment] 2023-05-23 00:24
@t-will-gillis @Sebster3 Sorry if I didn't call this out the other day... What is supposed to happen after the changes all identified.  Are issues going to be created?  This issue doesn't specify it


Order
- This issue 4525, creates the list of changes needed.  Finishing this issue releases the dependency on XXXX
- new issue XXXX, takes the list and makes new issues to make the changes to each use (previously identified) (labels `issue making: level 2 or 3` `dependency`) (once this issue is created, please add a checkbox at the bottom of the action items on 4525 to release this issue from the icebox and put this issue in the icebox)
  - TBD issue 1 projects page changes to use new data structure
  - TBD issue 2 project profile page
  - TBD etc. if there are any other uses of tools
-  #4427, makes a new tool filter for the projects/home page (has the dependency of issues 4525, XXXX and its child issue related to the projects page above)

**Comment by Sebster3** [comment] 2023-05-24 15:50
Hi, @ExperimentsInHonesty, based on my understanding of the roll-out plan outlined in issue #4523, this issue focuses on documenting the required information for generating the remaining outlined issues. However, it does not include any requests for changes itself.

Once the documentation is produced from this issue, I can move forward and begin writing out the parent issue on the second top-level bullet point of the roll out plan which leads into the rest of the smaller issues addressing each of the changes needed.

If I'm misunderstanding the flow of events, I'd like to get on a call or wait until Sunday's meeting (if that isn't too long of a wait) so I can get a better understanding.

**Comment by ExperimentsInHonesty** [comment] 2023-06-04 13:58
@Sebster3 thanks. I updated the instructions for merge team in the body, to say when the issue is complete instead of when the pr for this issue is merged.

**Comment by 93Belen** [comment] 2023-06-04 16:40
Availability: Monday, Tuesday and Sunday
ETA: Tuesday by 6pm

**Comment by ronaldpaek** [comment] 2023-06-08 07:06
i. Availability: 6/11 - 6/13
ii. ETA:  Not sure when I will finish, am I never done a task this big, 6/13, if not hopefully the next week will check in and ask for help if I run any blockers

**Comment by ronaldpaek** [comment] 2023-06-13 23:36
1. 6/13/23
2. 6/13/23

Hello I am not sure how to proceed, I made a google docs, but not 100% if I wrote this correctly and not sure how to upload it to hack4la google drive and where to place it.

https://docs.google.com/document/d/1IEazMdDmDd86SUoQEBduKCsfOgUBnEZQKOM_ZPBnrCI/edit?usp=sharing

**Comment by ronaldpaek** [comment] 2023-06-14 02:49
@t-will-gillis tagging you, please let me know what I should do, I wasn't sure how to create a PR for this

**Comment by t-will-gillis** [comment] 2023-06-14 19:38
Hey @ronaldpaek - your report looks great! It identifies:

- the 17 +/- markdown files in the `/_projects/` folder that include the tools data,
- the proposed refactoring of the code in the [project.html](https://github.com/hackforla/website/blob/gh-pages/_layouts/project.html) file to use the newly formatted tools,
- the proposed refactoring of the code in the [current-projects.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js) file to use the newly formatted tools, and
- the proposed refactoring of the code in the [current-projects-check.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects-check.js) file to use the newly formatted tools.

I am closing this issue as completed, and releasing the dependency on the next issue. Thank you for your work on this issue!

**Closed as completed by t-will-gillis** 2023-06-14 19:38 UTC
Labels: role: front end, role: back end/devOps, Complexity: Large, time sensitive, status: Updated, Feature: Refactor JS / Liquid, size: 2pt, p-feature: Projects-check
