### ISSUE TITLE
Fix Communities of Practice page header image size

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1793] opened 2021-06-20 07:48 UTC
### Overview
We need to fix the Communities of Practice page's header image so that it matches the original Figma design, and looks more proportional with the text

### Action Items
- [x] Figure out why the header image in the [Communities of Practice](https://www.hackforla.org/communities-of-practice) page is currently 300x240 size when it is supposed to be 384x240
- [x] Fix to make sure it now has the correct measurements

### Resources/Instructions
[Communities of Practice page](https://www.hackforla.org/communities-of-practice)
[Hack for LA site architecture ](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture)

How header image looks now (incorrect- too small - 300px width)
<img width="720" alt="Screen Shot 2021-06-20 at 12 41 48 AM" src="https://user-images.githubusercontent.com/67400366/122666218-ee4cac80-d160-11eb-9857-061b006b01a4.png">

How header image is supposed to look (correct- 384px width)- I got this to be correct here in inspect element when I tested changing the font size- suddenly the image turned into the correct size. Then I switched the font size back to its original size, and the image stayed large (the correct size). Not sure what that means...
<img width="720" alt="Screen Shot 2021-06-20 at 12 41 58 AM" src="https://user-images.githubusercontent.com/67400366/122666212-e12fbd80-d160-11eb-90b9-4fc90adbea07.png">

**Comment by ghost** [comment] 2021-06-29 22:54
The issue was computed prior and looks like no additional fixing is needed.
<img width="1440" alt="Screen Shot 2021-06-29 at 6 51 36 PM" src="https://user-images.githubusercontent.com/74923247/123877545-635f7500-d90b-11eb-80f4-07166b400e21.png">

**Comment by Sihemgourou** [comment] 2021-07-04 17:21
@daniellex0 the team concluded that the images are already in the right size. Did we miss something ? If it's fine, please close this issue :)

**Comment by daniellex0** [comment] 2021-07-11 15:38
@Sihemgourou Weird, for some reason sometimes it looks normal, but usually it looks too small (still).

However then if I do inspect element for mobile view and then go back to desktop, it looks right.

Not sure what is going on...?

I'll try to show how it looks during today's meeting

**Comment by macho-catt** [comment] 2021-07-12 22:06
I briefly took a look at this because it seemed interesting, although I can't work on it because I have another PR opened at the moment.

I was able to reproduce this issue on chrome and edge, but not firefox (could not test on safari).
So I took a closer look at the CSS. At first, for the class "header-img--communities" I set the max-width to 384px and width to 100% to force it to use 384px on the first render, with the proper adjustments based on the media queries. This fixed the width issue on chrome. However, it was weird that it's only happening to this svg and not the other ones on the site. It's also weird that firefox was not having this issue.

Then I noticed that the SVG is wrapped in an object tag instead of an img tag. The only other SVG wrapped in an object tag is the slack icon in the same page, and that one was not exhibiting issues because a width was set for it in the CSS (24px). So I changed the wrapping tag from <object> to <img> and removed the max-width and width properties I set under the class "header-img--communities." After doing that, it looks like the issue is fixed on chrome.

I didn't do any further research on the issue, but I wonder if chrome and edge have some issues with the object tag. Additionally, is there a specific reason we're using the object tag for this page and not the img tag?

**Comment by Abel-Zambrano** [comment] 2021-07-14 02:43
IMPORTANT!! 
This issue is working off of a feature branch!
Please follow this wiki before creating a new branch!
[how to work off a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)

**Comment by macho-catt** [comment] 2021-07-20 15:37
@daniellex0 I looked at this briefly. It looks like this occurs for chrome and microsoft edge, but not firefox. There are two possible fixes that I found for this:
1) You can set the class for the object that wraps the SVG to have a max-width of 384px and width of 100% so that for the desktop view, it is forced to take 384px on the first render and when the screen size changes it will change as well. But this might need some media query adjustments to ensure that the tablet and mobile views look good.
2) You can change the object tag that wraps the SVG to an img tag, and the issue is fixed. Looking through the site, only this page wraps an object tag for SVGs. All other pages use the img tag. Is there a reason for this?

**Closed as completed** 2021-07-21 06:54 UTC
Labels: Bug, role: front end, Complexity: Large, status: Updated, P-Feature: Communities of Practice, size: missing
