### ISSUE TITLE
Create 2.0.1 tag

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#122] opened 2019-05-27 23:20 UTC
## Overview

We need the next tag to assign to the next release

## Action Item

Create the tag 2.0.1

**Comment by thekaveman** [comment] 2019-05-28 16:29
Typically the tag is created *after* all the commits have been made for the release. E.g. if there are some open PRs for the next release, they should all be merged into `gh-pages`, then a tag created on the HEAD.

Tag creation has to be done locally (and to push, you have to have write access on this repo):

```bash
git checkout gh-pages
git fetch && git pull
git tag 2.0.1
git push --tags
```

Once the tag is pushed, you can start [drafting a new release](https://github.com/hackforla/website/releases/new) based on the tag.

**Comment by thekaveman** [comment] 2019-05-28 17:00
Closing as a duplicate of #120.

**Closed as completed by thekaveman** 2019-05-28 17:00 UTC
Labels: Feature: Administrative, Ignore: Duplicate
