### ISSUE TITLE
Create a Code of Conduct Page

### ISSUE THREAD

**Issue by abregorivas** [hackforla/website#110] opened 2019-05-21 05:57 UTC
### Dependency
Tabling for now due to lift required and release of VRMS 0.4 - you can check vrms by opening in a browser window https://vrms.io

### Overview
We want to add people seeing / agreeing with the code of conduct before they can get a slack invite, without making it prone to breaking if CfA changes code of conduct that we are forking.

### Background
HFLA code of conduct is located at https://github.com/hackforla/codeofconduct

### Original ask
 **- but we have revised since then - see comments below in issue:**
We need to add this to a page on the website.
This issue is site page called that holds our code of conduct.
The page should have an an accept / decline button at the bottom.
Accept button redirects to https://hackforla-slack.herokuapp.com/
Decline button redirects back to home page

**Comment by thekaveman** [comment] 2019-05-22 22:53
@abregorivas @ddrosario sorry if I missed a convo at DTLA, but I'm not sure I agree with this approach of porting the CoC into the website. 

The reason it is in the repo is because this was Code for America's CoC, and we as a Brigade forked it. They have subsequently updated the upstream, and added some additional docs around Slack usage and the expectations at Summit (the CfA conference). In my mind, we should be keeping up to date with upstream via our fork, rather than trying to reproduce content in multiple places.

Now making sure people accept before using Slack and all that - makes total sense. But since this content has a lineage that didn't begin with us, can we find a way to keep that intact?

**Comment by ExperimentsInHonesty** [comment] 2019-05-23 03:35
@thekaveman I agree about replicating the content and then it getting out of date is not the ideal way to do it.  Do you have another way that we can accomplish an attractive version of the code of conduct, and insert it into the click stream so that they don't get a slack invite without agreeing to it?

**Comment by ExperimentsInHonesty** [comment] 2019-05-23 03:37
p.s. I added people from the team that I thought could benefit from the planning part of this issue from UI/UX to implementation and stability.  This is a good issue to see how and why we make the decisions we do.

**Comment by thekaveman** [comment] 2019-05-23 23:01
The "attractiveness" of the content should be a secondary concern; the words themselves are what matter here. 

I think we should go all the way down the stack to the Heroku app that sends the Slack invite link. Rather than try and hijack the click stream with redirects everywhere, I'd rather we build this directly into the sign-up app so we know it is part of the flow. 

**EDIT:** i think this is the app that powers the sign-up: https://github.com/rauchg/slackin

**Comment by ExperimentsInHonesty** [comment] 2019-05-27 20:20
Let's talk about this post Summit.  And possibly table this until after we figure out what the plan for the site is moving forward

**Comment by matikin9** [comment] 2019-08-14 23:23
Hi everyone - I just wanted to comment that I've updated the app the runs the slack invite.  It's now using: https://github.com/emedvedev/slackin-extended

To add the Code of Conduct directly, we'll have to fork that repo and then make our changes.  I'll deploy the new version to the Heroku account running the app.

In the meantime, can we add a link on the website to our existing Code of Conduct?

**Comment by ExperimentsInHonesty** [comment] 2020-06-01 02:32
Hi @matikin9 , sorry this issue got iceboxed.  We do still want to add people agreeing to the code of conduct before getting a slack invite.  It seems from your last post that you might be able to help with that: https://github.com/hackforla/website/issues/110#issuecomment-521455617

**Comment by alexandrastubbs** [comment] 2020-07-10 18:14
Email sent to Nina to source more information on a possible solution.

**Comment by alexandrastubbs** [comment] 2020-07-12 15:49
Spoke w/ Nina and will look into creating something similar to Code for America's slack sign up: http://slack.codeforamerica.org

Need to consider what other information needs to be collected at this point in time and if any of it is redundant to the other surveys that we share out.

**Comment by alexandrastubbs** [comment] 2020-07-14 13:42
In thinking through when an individual would encounter this survey, we have two viable options for where to put the code of conduct: 

1. Add it into the Remote Onboarding Survey
2. Create a survey to replace slack self sign-up and roll both code of conduct and slack sign-up into this step 

First is preferred, but depends on how many individuals actually complete this survey. We could try to make this a mandatory step before signing up for slack, in an effort to elicit more onboarding survey participation. If we go the second route, then we can make the 'survey' a simple question about accepting code of conduct and if they answer yes, we can redirect to slack self sign-up. 

Next step: Chat with @ExperimentsInHonesty about which option is better given current behaviors today. 

<img width="464" alt="Screen Shot 2020-07-14 at 9 28 37 AM" src="https://user-images.githubusercontent.com/66918724/87432750-65bfa680-c5b6-11ea-925d-6462c9f8169a.png">

**Comment by alexandrastubbs** [comment] 2020-07-15 22:59
Tabling for now due to lift required and release of VRMS.

**Comment by ExperimentsInHonesty** [comment] 2023-03-16 16:38
@jdingeman @chriskong217 We will no longer be bound by the Code for America code of conduct as of June.  So we can update our own code of conduct and place it in a friendlier format on the website.  

The content should still live in a CODEOFCONDUCT.md file in our repo, but we can detach it from CfA, clean it up, and then it can display as a webpage on our site.  

Please keep in mind that we might want to add/edit its content, so it should be as easy as possible to edit (i.e., markdown)

Steps (that will need issues)...
- Review the diff between CfA's current Code of Conduct and ours.  
https://github.com/hackforla/codeofconduct
<img src="https://user-images.githubusercontent.com/37763229/225687441-30f066c0-e9c1-4df6-aa2e-847a5b63b2a6.png" width=300px>
- Identify what changes we will be making when it's June 1st and create a new readme-june2023.md file to take the place of the existing when it's time.
- Make the markdown https://github.com/hackforla/codeofconduct/blob/master/README.md file appear on the website as a hackforla.org/conduct (currently that URL is a redirect) formatted automatically without resorting to creating a hard-coded HTML page (e.g. of a hard-coded HTML page that should be a markdown file automatically turned into HTML, so It's easy to edit the markdown https://github.com/hackforla/website/blob/gh-pages/pages/privacy-policy.html)

**Comment by ExperimentsInHonesty** [comment] 2023-03-22 18:58
- I am closing this issue, and have made an ER https://github.com/hackforla/website/issues/4243.  We now only give the slack link out during onboarding.

**Closed as completed** 2023-03-22 18:58 UTC
Labels: Complexity: Medium, size: 1pt, feature: code of conduct, role missing
