### ISSUE TITLE
Adjust Donate Page - Fix Green Circles

### ISSUE THREAD

**Issue by kristine-eudey** [hackforla/website#2079] opened 2021-08-10 15:20 UTC
### Overview
We need to adjust the Donate page to make it fit with the design system and similar information on the Join Us page 
### Action Items
- [x] Make the green circles illustration (Monthly/Annual/Occasional etc) match the illustration at the bottom of the [Join Us page](https://www.hackforla.org/join). For some reason the version in the Donate page has black border around the circles, but this shouldn’t be the case- it should be the exact same image file as the Join Us page one and should look like the Join Us page version
### Resources/Instructions
[Join Us page](https://www.hackforla.org/join)
![Screen Shot 2021-08-08 at 2 40 37 AM](https://user-images.githubusercontent.com/67400366/128627927-415db64c-9291-4061-9422-baa28e15987d.png)

**Comment by arghmatey** [comment] 2021-08-18 05:09
@kristine-eudey The first action item is a duplicate of #2084. Can you please adjust this issue to be fixing the green circles only?

**Comment by kristine-eudey** [comment] 2021-08-22 18:04
@arghmatey The issue has been updated to refer only to fixing the green circles.

**Closed as completed** 2021-08-28 05:48 UTC
Labels: role: front end, status: Updated, P-Feature: Donate, Complexity: Small, size: missing
