### ISSUE TITLE
Hide "Looking for" from project cards 

### ISSUE THREAD

**Issue by kristine-eudey** [hackforla/website#1997] opened 2021-07-21 16:56 UTC
### Overview
We need to hide "Looking for" from project cards because this information is rarely accurate / up to date. Keep the code/functionality in case this needs to be reversed in the future. 

### Action Items
- [ ] UI/UX
  - [x] Duplicate this [Figma page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=7829%3A40586) and remove the pink tags line to start from the initial state. 
  - [x] Remove "Looking" filter and redesign that line to accommodate just the 3 remaining filters. 
  - [x]  Share link to figma design in comment on this issue to show developers what the to-be state is
  - [x] Add before and after images to this issue under Resources section

- [x] Front End
   - [x] Hide "Looking for" from project cards on homepage.
   - [x] Hide "Open Roles" in Project Description pages
   - [x] Hide "Looking" filter dropdown on homepage
      - [x] Evenly space three remaining filters

### Resources/Instructions
https://www.hackforla.org/#
[Figma File - Homepage](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=7829%3A40586)

**Comment by kristine-eudey** [comment] 2021-07-30 18:56
ETA - Sunday 8/1

**Comment by kristine-eudey** [comment] 2021-08-01 16:26
Please remove "Looking" from filter bar as shown in this [Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-febsite?node-id=13299%3A90788) file.
 
**Before:**
<img width="646" alt="issue #1997 before" src="https://user-images.githubusercontent.com/16949503/127778156-77976871-5440-4030-9d0d-ef785b3f350f.png">

**After:**
<img width="590" alt="ussue #1997 after" src="https://user-images.githubusercontent.com/16949503/127778255-67a68624-aa8e-415e-8d8e-f86f6340dcc9.png">

**Comment by Aveline-art** [comment] 2021-08-02 01:28
Hi @vickiychung . Please do not remove your assignment from an issue unless you are no longer working on it. If you have a linked pull request still open, the issue is still assigned to you until it is merged. This helps us sort out the issues when we maintain the project board. Thank you!

**Closed as completed** 2021-08-03 03:06 UTC
Labels: role: front end, P-Feature: Project Info and Page, Complexity: Small, size: missing
