### ISSUE TITLE
Update Project Profile: Add Mario Antonini to Merge Team

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#6864] opened 2024-05-20 20:08 UTC
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Hackforla.org Website project page needs to be updated so that the project information is up to date. 

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/website.md` file and find the `leadership` variable.
- [x] Add the new team members `name`, `github-handle`, `role`, `slack` link, `github` link, and `picture` to the end of the `leadership` variable
```
  - name: Mario Antonini
    github-handle: 
    role: Merge Team
    links:
      slack: 'https://hackforla.slack.com/team/U06MTPZ67V3'
      github: 'https://github.com/marioantonini'
    picture: https://avatars.githubusercontent.com/marioantonini
    
```

- [x] Verify the changes by viewing the [Hackforla.org Website project page](https://www.hackforla.org/projects/website) on your local environment and include a screenshot with your pull request

### Resources
- [website.md](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)
- [Hackforla.org Website project page](https://www.hackforla.org/projects/website

**Comment by ExperimentsInHonesty** [comment] 2024-05-26 18:50
@roslynwythe I am not sure what I am supposed to do with this issue.  
It seems like all the checkboxes have been checked, which I would assume that means the issue is completed but I don't see a pr associated with it.
- [ ] if the issue is complete, find and link the PR and then close the issue
 - [x] If the issue is not complete, please check this box and do the following
    - [x] uncheck the boxes
    - [x] hide this comment the comment above.
    - [x] remove the `ready for dev lead` label
    - [x] add the `ready for proritization` label

**Closed as completed** 2024-06-05 20:27 UTC
Labels: good first issue, role: front end, role: back end/devOps, P-Feature: Project Info and Page, size: 0.25pt
