### ISSUE TITLE
Fix Project Profile page bug: Technologies not wrapping

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#2754] opened 2022-02-09 01:47 UTC
### Overview
We need the Technologies line to wrap the same way that the Languages does, so that it does not collide with the Description text

#### Details
All the project pages are controlled by one layout. Do not edit the code for a single project, but rather the layout page.

### Action Items
- [x] Review the Civic Tech Jobs project page
- [x] Review the 311-data project page
- [x] Figure out the problem
  - [x] Since `id="technologies"` is being used by both the Languages/Technologies dropdown and the technologies field on the detail project profile pages, the SCSS `#technologies` was being applied to all elements with `id="technologies"` throughout the website. 
- [x] Fix the problem 
  - [x] Temporary fix: Revert the pr causing it
  - [x] Actual fix: Change the `#technologies` SCSS to `ul.dropdown#technologies`. 
    - Note: This was merged into the branch: feature-tech-dropdown because it was realized that the dropdown was static and could only support a certain number of menu items, which Jessica will write an issue for to address. Also, changes were made to fix an issue with gaps caused by having 4 columns and we want approval from design to see if that's okay. 
- [x] Submit PR

### Resources/Instructions
<details>
<summary>Example image from Civic Tech Jobs page</summary>

![image](https://user-images.githubusercontent.com/37763229/153107196-d6d868c8-1edd-4014-a779-01a43b434d71.png)

</details>

Pages that have longer Technologies categories
- https://www.hackforla.org/projects/civic-tech-jobs
- https://www.hackforla.org/projects/311-data
- https://www.hackforla.org/projects/civic-tech-index
- https://www.hackforla.org/projects/food-oasis

**Comment by JessicaLucindaCheng** [comment] 2022-02-09 02:51
- Availability: 2 hours
- ETA: Today (February 8, 2022)

**Comment by JessicaLucindaCheng** [comment] 2022-02-09 07:29
- Progress: I figured out what was causing the problem. It was caused by `id="technologies"` being used by both the Languages/Technologies dropdown and the technologies field on the detail project profile page. PR #2757 will fix the issue by reverting the SCSS changes in the technologies dropdown that caused the problem. However, this is only a temporary fix and the issue with the `id="technologies"` would still need to be addressed.
- Blockers: I'm tired and don't have the brainpower at the moment to address the root of the problem with `id="technologies"`.
- Availability: All day on Wed, Feb 9, 2022
- ETA: Wed, Feb 9, 2022 (To possibly figure out a solution for the problem with `id="technologies"`.)

**Comment by JessicaLucindaCheng** [comment] 2022-02-09 15:24
Reopening this because the root of the problem with `id="technologies"` has not been addressed.

**Comment by JessicaLucindaCheng** [comment] 2022-02-10 22:34
- Progress: Fixed the problem and opened a pr to address the issue
- Blockers: None
- Availability: Will update if changes are requested
- ETA: Will update if changes are requested

**Comment by JessicaLucindaCheng** [comment] 2022-03-12 22:46
Note root of problem was fixed in pr #2761 and was merged on to the feature branch `feature-tech-dropdown`.

**Closed as completed by JessicaLucindaCheng** 2022-03-12 22:46 UTC
Labels: Bug, role: front end, Complexity: Medium, P-Feature: Project Info and Page, status: Updated, size: 1pt
