### ISSUE TITLE
Update Project Profile: ACCESS THE DATA

### ISSUE THREAD

**Issue by mxajPrice** [hackforla/website#4938] opened 2023-07-11 17:55 UTC
### Project Name

Access The Data

### Project Card URL

access-the-data.md

### Update the Title?

NO

### Update the Description?

NO

### Update the Image?

NO

### Update the Technologies?

NO

### Update the Partner(s)?

NO

### Update the Tools?

NO

### Update GitHub Link?

NO

### Update Slack Link?

NO

### Update Test Site Link?

NO

### Update Demo Site Link?

NO

### Update Site Link?

NO

### Remove person(s) and info from Leadership?

YES

### If YES on remove person(s), edit the below to provide the information required. If NO, delete the template in the field below:

Name: Leslie Luk
Name: Bonnie Wolfe

### Add person(s) and info to Leadership?

YES

### If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:

Name: Jason Yung
GitHub Handle: @merlinsmagic 
Role: Project Manager
Slack Member ID: U059W9P96C8

### Project Status

Active

**Comment by ExperimentsInHonesty** [comment] 2023-07-18 00:10
- I am closing this as it seems like its a duplicate of https://github.com/hackforla/website/issues/4939

**Closed as not planned** 2023-07-18 00:10 UTC
Labels: role: front end, role: back end/devOps, P-Feature: Project Info and Page, time sensitive, ready for dev lead, size: 0.5pt, Ignore: Duplicate
