### ISSUE TITLE
About Us -> Fix shrinking images in SDG section

### ISSUE THREAD

**Issue by drubgrubby** [hackforla/website#861] opened 2020-12-22 02:53 UTC
### Overview
In SDG section, left row of images gets smaller when minimizing the page before it switches over to mobile view.

<img width="643" alt="Screen Shot 2020-12-10 at 1 03 16 PM" src="https://user-images.githubusercontent.com/68244054/101829677-3a4ed280-3ae8-11eb-99c4-931ac79410cf.png">

### Action Items
Make it stop doing that.

### Resources/Instructions
https://www.hackforla.org/about-us

**Comment by shaswa** [comment] 2021-03-17 18:28
@drubgrubby Why is this issue in the Ice Box? Can it be moved to the prioritized backlog?

**Comment by drubgrubby** [comment] 2021-03-17 18:38
@shaswa -> I have no idea why it's in icebox. I'm guessing there were dependencies that were removed, but it wasn't recategorized.  I will move it to prioritized backlog.

**Comment by trtincher** [comment] 2021-03-28 15:15
Status: Have started it still looking into the issue.
Eta: 4/3/21
Availability: Evenings, weekends mostly.

**Comment by trtincher** [comment] 2021-04-05 14:07
Unfortunately I am going to have to step back for a while from working on issues. Life and work have become a bit much to keep up with the extra work.

**Comment by qiqicodes** [comment] 2021-04-11 17:24
Progress: Trying to replicate the bug in the current code base. The ratio of shrinking image is not as drastic as image shown in the issue.

Blockers: None.

Availability: Open on Tuesday and Friday evening.

ETA: 4/18/21

**Comment by averdin2** [comment] 2021-04-14 20:08
The issue is that there is text on the bottom right image in the grid. CSS Grid will not resize the text, and since that text is tied to the element in the grid, it will not resize the right side grid elements to fit the space it needs.

I am still thinking about fixes.

**Comment by averdin2** [comment] 2021-04-15 19:15
As stated in my previous comment, the issue has to do with the text in the grid not being resizable. I have come up with a few solutions, and possible suggestions for changes that should be discussed with the team that are listed below:
1. Remove the text. Removing the text makes all the images size properly, but then the external link is gone.
2. Make the picture with text itself an entire image rather than having separate text. We could then make the image itself a link.
3. We can also leave as is, but would need to change the width of the grid so it can resize properly.

There are also some other considerations I think the team should think about. 
- The other images are not links as well, but maybe they should be? If you go to that link in question (https://sdg.lamayor.org/), you can see that their images are links. If we decide to do this, we also need to think about what those links are. Josh mentioned that we are trying to focus on having more links reference our site internally rather than linking to external sites, so what would those links look like?

**Comment by averdin2** [comment] 2021-04-19 21:22
Changes made in merged PR #1420 seems to have broken mobile responsiveness on the About page. See screenshot below.
![image](https://user-images.githubusercontent.com/10714770/115305034-91aa2280-a11a-11eb-8e7f-6d41a6b29ac1.png)

**Comment by averdin2** [comment] 2021-04-19 23:11
I added some spacing for numbers and text in the SDG section of about page, as the numbers and text were becoming cramped around the 970px width range. There is a little extra spacing when on a normal desktop viewport range. See screenshots below.

<details>
<summary>Screenshots</summary>

Less cramping in tablet range

![image](https://user-images.githubusercontent.com/10714770/115314177-8e6a6300-a129-11eb-9ecc-4a591dd0591d.png)

A little extra room in larger desktop viewport ranges.
![image](https://user-images.githubusercontent.com/10714770/115314263-b0fc7c00-a129-11eb-8350-0833e5a2e362.png)


</details>

**Comment by averdin2** [comment] 2021-04-19 23:31
Aligned LA Mayor link so that it is centered with the left side images in the SDG section. I'm thinking maybe the text of that link should be bigger?
![image](https://user-images.githubusercontent.com/10714770/115315448-36812b80-a12c-11eb-8318-16bedb1201fd.png)

**Closed as completed** 2021-04-30 16:37 UTC
Labels: Bug, role: front end, P-Feature: About Us, status: Updated, size: missing, Complexity: Missing
